<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Compression.Mounting.Dokan</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DokanNet" Version="2.3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Compression.Mounting\Compression.Mounting.csproj" />
  </ItemGroup>

</Project>
