<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Codec.Xma</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Compression.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Codec.WmaPro\Codec.WmaPro.csproj" />
  </ItemGroup>

</Project>
