using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Compression.Registry.Generator;

/// <summary>
/// Roslyn incremental source generator that discovers all public non-abstract types implementing
/// IFormatDescriptor across referenced assemblies and generates:
/// 1. A partial FormatRegistration class with explicit constructor calls (zero reflection)
/// 2. A Format enum inside FormatDetector with all discovered format IDs plus special values
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FormatDescriptorGenerator : IIncrementalGenerator {

  private const string InterfaceFullName = "Compression.Registry.IFormatDescriptor";

  /// <summary>
  /// Special enum members that are always generated even though they have no descriptor.
  /// Unknown = no format detected; Sfx/Iso/Udf = detected by special logic, not a registry descriptor.
  /// </summary>
  private static readonly string[] SpecialFormats = [
    "Unknown", "Sfx", "Iso", "Udf",
    // Compound tar formats — registered manually in FormatRegistration.RegisterCompoundTar()
    "TarGz", "TarBz2", "TarXz", "TarZst", "TarLz4", "TarLzip", "TarBr",
  ];

  public void Initialize(IncrementalGeneratorInitializationContext context) {
    var descriptorTypes = context.CompilationProvider.Select((compilation, ct) => {
      var descriptorInterface = compilation.GetTypeByMetadataName(InterfaceFullName);
      if (descriptorInterface == null)
        return new List<(string FullName, string Id)>();

      var results = new List<(string FullName, string Id)>();

      // Check all referenced assemblies
      foreach (var reference in compilation.References) {
        if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assembly)
          continue;
        FindDescriptors(assembly.GlobalNamespace, descriptorInterface, results, ct);
      }

      // Also check the compilation's own types
      FindDescriptors(compilation.Assembly.GlobalNamespace, descriptorInterface, results, ct);

      results.Sort((a, b) => StringComparer.Ordinal.Compare(a.FullName, b.FullName));
      return results;
    });

    context.RegisterSourceOutput(descriptorTypes, static (spc, types) => {
      EmitFormatRegistration(spc, types);
      EmitFormatEnum(spc, types);
    });
  }

  private static void EmitFormatRegistration(SourceProductionContext spc, List<(string FullName, string Id)> types) {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("using Compression.Registry;");
    sb.AppendLine();
    sb.AppendLine("namespace Compression.Lib;");
    sb.AppendLine();
    sb.AppendLine("internal static partial class FormatRegistration {");
    sb.AppendLine("  static partial void RegisterFormats() {");
    foreach (var (fullName, _) in types) {
      sb.AppendLine($"    FormatRegistry.Register(new {fullName}());");
    }
    sb.AppendLine("  }");
    sb.AppendLine("}");

    spc.AddSource("FormatRegistration.g.cs", sb.ToString());
  }

  private static void EmitFormatEnum(SourceProductionContext spc, List<(string FullName, string Id)> types) {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine();
    sb.AppendLine("namespace Compression.Lib;");
    sb.AppendLine();
    sb.AppendLine("internal static partial class FormatDetector {");
    sb.AppendLine("  internal enum Format {");

    // Special values first
    foreach (var special in SpecialFormats) {
      sb.AppendLine($"    {special},");
    }

    // All discovered descriptor IDs (excluding any that match special values)
    var specialSet = new HashSet<string>(SpecialFormats);
    foreach (var (_, id) in types) {
      if (!specialSet.Contains(id)) {
        sb.AppendLine($"    {id},");
      }
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");

    spc.AddSource("FormatDetector.Format.g.cs", sb.ToString());
  }

  private static void FindDescriptors(
      INamespaceSymbol ns,
      INamedTypeSymbol descriptorInterface,
      List<(string FullName, string Id)> results,
      System.Threading.CancellationToken ct) {
    foreach (var member in ns.GetMembers()) {
      ct.ThrowIfCancellationRequested();
      if (member is INamespaceSymbol childNs) {
        FindDescriptors(childNs, descriptorInterface, results, ct);
      } else if (member is INamedTypeSymbol type &&
                 type.TypeKind == TypeKind.Class &&
                 !type.IsAbstract &&
                 type.DeclaredAccessibility == Accessibility.Public &&
                 HasParameterlessConstructor(type) &&
                 Implements(type, descriptorInterface)) {
        var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var id = DeriveId(type.Name);
        results.Add((fullName, id));
      }
    }
  }

  /// <summary>
  /// Derives the format ID from the class name by stripping the "FormatDescriptor" suffix.
  /// E.g., "GzipFormatDescriptor" → "Gzip", "SevenZipFormatDescriptor" → "SevenZip".
  /// </summary>
  private static string DeriveId(string className) {
    const string suffix = "FormatDescriptor";
    if (className.EndsWith(suffix))
      return className.Substring(0, className.Length - suffix.Length);
    return className;
  }

  private static bool HasParameterlessConstructor(INamedTypeSymbol type) {
    foreach (var ctor in type.Constructors) {
      if (!ctor.IsStatic &&
          ctor.DeclaredAccessibility == Accessibility.Public &&
          ctor.Parameters.Length == 0)
        return true;
    }
    return false;
  }

  private static bool Implements(INamedTypeSymbol type, INamedTypeSymbol iface) {
    foreach (var i in type.AllInterfaces) {
      if (SymbolEqualityComparer.Default.Equals(i, iface))
        return true;
    }
    return false;
  }
}
