using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Compression.Registry.Generator;

/// <summary>
/// Roslyn incremental source generator that discovers all public non-abstract types implementing
/// IFormatDescriptor and IBuildingBlock across referenced assemblies and generates:
/// 1. A partial FormatRegistration class with explicit constructor calls (zero reflection)
/// 2. A Format enum inside FormatDetector with all discovered format IDs plus special values
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FormatDescriptorGenerator : IIncrementalGenerator {

  private const string DescriptorInterfaceFullName = "Compression.Registry.IFormatDescriptor";
  private const string BuildingBlockInterfaceFullName = "Compression.Registry.IBuildingBlock";

  /// <summary>
  /// Special enum members that are always generated even though they have no descriptor.
  /// Unknown = no format detected; Sfx/Iso/Udf = detected by special logic, not a registry descriptor.
  /// </summary>
  private static readonly string[] SpecialFormats = [
    "Unknown", "Sfx", "Iso", "Udf",
    // Compound tar formats — registered manually in FormatRegistration.RegisterCompoundTar()
    "TarGz", "TarBz2", "TarXz", "TarZst", "TarLz4", "TarLzip", "TarBr",
  ];

  public void Initialize(IncrementalGeneratorInitializationContext context) {
    var allTypes = context.CompilationProvider.Select((compilation, ct) => {
      var descriptorInterface = compilation.GetTypeByMetadataName(DescriptorInterfaceFullName);
      var buildingBlockInterface = compilation.GetTypeByMetadataName(BuildingBlockInterfaceFullName);

      var descriptors = new List<(string FullName, string Id)>();
      var buildingBlocks = new List<string>();

      if (descriptorInterface != null || buildingBlockInterface != null) {
        // Check all referenced assemblies
        foreach (var reference in compilation.References) {
          if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assembly)
            continue;
          FindTypes(assembly.GlobalNamespace, descriptorInterface, buildingBlockInterface, descriptors, buildingBlocks, ct);
        }

        // Also check the compilation's own types
        FindTypes(compilation.Assembly.GlobalNamespace, descriptorInterface, buildingBlockInterface, descriptors, buildingBlocks, ct);
      }

      descriptors.Sort((a, b) => StringComparer.Ordinal.Compare(a.FullName, b.FullName));
      buildingBlocks.Sort(StringComparer.Ordinal);
      return (Descriptors: descriptors, BuildingBlocks: buildingBlocks);
    });

    context.RegisterSourceOutput(allTypes, static (spc, types) => {
      EmitFormatRegistration(spc, types.Descriptors, types.BuildingBlocks);
      EmitFormatEnum(spc, types.Descriptors);
    });
  }

  private static void EmitFormatRegistration(SourceProductionContext spc,
      List<(string FullName, string Id)> descriptors, List<string> buildingBlocks) {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("using Compression.Registry;");
    sb.AppendLine();
    sb.AppendLine("namespace Compression.Lib;");
    sb.AppendLine();
    sb.AppendLine("internal static partial class FormatRegistration {");
    sb.AppendLine("  static partial void RegisterFormats() {");
    foreach (var (fullName, _) in descriptors) {
      sb.AppendLine($"    FormatRegistry.Register(new {fullName}());");
    }
    sb.AppendLine("  }");
    sb.AppendLine();
    sb.AppendLine("  static partial void RegisterBuildingBlocks() {");
    foreach (var fullName in buildingBlocks) {
      sb.AppendLine($"    BuildingBlockRegistry.Register(new {fullName}());");
    }
    sb.AppendLine("  }");
    sb.AppendLine("}");

    spc.AddSource("FormatRegistration.g.cs", sb.ToString());
  }

  private static void EmitFormatEnum(SourceProductionContext spc, List<(string FullName, string Id)> types) {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine();
    sb.AppendLine("namespace Compression.Lib;");
    sb.AppendLine();
    sb.AppendLine("internal static partial class FormatDetector {");
    sb.AppendLine("  internal enum Format {");

    // Special values first
    foreach (var special in SpecialFormats) {
      sb.AppendLine($"    {special},");
    }

    // All discovered descriptor IDs (excluding any that match special values)
    var specialSet = new HashSet<string>(SpecialFormats);
    foreach (var (_, id) in types) {
      if (!specialSet.Contains(id)) {
        sb.AppendLine($"    {id},");
      }
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");

    spc.AddSource("FormatDetector.Format.g.cs", sb.ToString());
  }

  private static void FindTypes(
      INamespaceSymbol ns,
      INamedTypeSymbol? descriptorInterface,
      INamedTypeSymbol? buildingBlockInterface,
      List<(string FullName, string Id)> descriptors,
      List<string> buildingBlocks,
      System.Threading.CancellationToken ct) {
    foreach (var member in ns.GetMembers()) {
      ct.ThrowIfCancellationRequested();
      if (member is INamespaceSymbol childNs) {
        FindTypes(childNs, descriptorInterface, buildingBlockInterface, descriptors, buildingBlocks, ct);
      } else if (member is INamedTypeSymbol type &&
                 type.TypeKind == TypeKind.Class &&
                 !type.IsAbstract &&
                 type.DeclaredAccessibility == Accessibility.Public &&
                 HasParameterlessConstructor(type)) {
        var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (descriptorInterface != null && Implements(type, descriptorInterface)) {
          var id = DeriveId(type.Name, "FormatDescriptor");
          descriptors.Add((fullName, id));
        }

        if (buildingBlockInterface != null && Implements(type, buildingBlockInterface)) {
          buildingBlocks.Add(fullName);
        }
      }
    }
  }

  /// <summary>
  /// Derives the format ID from the class name by stripping a suffix.
  /// E.g., "GzipFormatDescriptor" → "Gzip", "SevenZipFormatDescriptor" → "SevenZip".
  /// </summary>
  private static string DeriveId(string className, string suffix) {
    if (className.EndsWith(suffix))
      return className.Substring(0, className.Length - suffix.Length);
    return className;
  }

  private static bool HasParameterlessConstructor(INamedTypeSymbol type) {
    foreach (var ctor in type.Constructors) {
      if (!ctor.IsStatic &&
          ctor.DeclaredAccessibility == Accessibility.Public &&
          ctor.Parameters.Length == 0)
        return true;
    }
    return false;
  }

  private static bool Implements(INamedTypeSymbol type, INamedTypeSymbol iface) {
    foreach (var i in type.AllInterfaces) {
      if (SymbolEqualityComparer.Default.Equals(i, iface))
        return true;
    }
    return false;
  }
}
