<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Compression.Mounting</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\Compression.Core\Hawkynt.Compression.Core.csproj" />
  </ItemGroup>

</Project>
