<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FileSystem.CbmNibble</RootNamespace>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Compression.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\FileSystem.D64\FileSystem.D64.csproj" />
  </ItemGroup>
</Project>
