namespace Hawkynt.Algorithms.Hashing;

internal static class HashSizeSets {
  internal static readonly IReadOnlyList<HashSizeRange> Bits32 = [HashSizeRange.Exact(32)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits64 = [HashSizeRange.Exact(64)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits128 = [HashSizeRange.Exact(128)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits160 = [HashSizeRange.Exact(160)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits192 = [HashSizeRange.Exact(192)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits224 = [HashSizeRange.Exact(224)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits256 = [HashSizeRange.Exact(256)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits320 = [HashSizeRange.Exact(320)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits384 = [HashSizeRange.Exact(384)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits512 = [HashSizeRange.Exact(512)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits32And64 = [new(32, 64, 32)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits32And128 = [HashSizeRange.Exact(32), HashSizeRange.Exact(128)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits64And128 = [new(64, 128, 64)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits128To256 = [new(128, 256, 32)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits224To512 = [new(224, 256, 32), new(384, 512, 128)];
  internal static readonly IReadOnlyList<HashSizeRange> Bits8To512 = [new(8, 512, 8)];
}

// Static extension members keep compatibility wrappers source-compatible while making the same
// Type.SupportedHashSizes surface available everywhere. Each receiver uses its own containing
// class because C# lowers static extension properties to parameterless getter methods.
public static class AsconHashSizeExtensions { extension(AsconHash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class BlakeHashSizeExtensions { extension(Blake) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits224To512; } }
public static class Blake2sHashSizeExtensions { extension(Blake2s) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class CityHashSizeExtensions { extension(CityHash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits64; } }
public static class Comb4PMd4Md5HashSizeExtensions { extension(Comb4PMd4Md5) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Comb4PSha1Ripemd160HashSizeExtensions { extension(Comb4PSha1Ripemd160) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits320; } }
public static class CubeHash256HashSizeExtensions { extension(CubeHash256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class CubeHash512HashSizeExtensions { extension(CubeHash512) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class DarkCryptMd6HashSizeExtensions { extension(DarkCryptMd6) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class DarkCryptSkeinHashSizeExtensions { extension(DarkCryptSkein) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class Echo224HashSizeExtensions { extension(Echo224) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits224; } }
public static class Echo256HashSizeExtensions { extension(Echo256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Echo384HashSizeExtensions { extension(Echo384) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits384; } }
public static class Echo512HashSizeExtensions { extension(Echo512) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class Esch256HashSizeExtensions { extension(Esch256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Esch384HashSizeExtensions { extension(Esch384) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits384; } }
public static class DarkCryptKeccakHashSizeExtensions { extension(DarkCryptKeccak) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class Gimli24HashSizeExtensions { extension(Gimli24Hash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class ChcHashSizeExtensions { extension(ChcHash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits128; } }
public static class Mdc2HashSizeExtensions { extension(Mdc2) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits128; } }
public static class FnvHashSizeExtensions { extension(Fnv) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits32And64; } }
public static class MurmurHash3HashSizeExtensions { extension(MurmurHash3) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits32And128; } }
public static class SipHash24HashSizeExtensions { extension(SipHash24) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits64; } }
public static class Gost3411HashSizeExtensions { extension(Gost3411_94) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Groestl224HashSizeExtensions { extension(Groestl224) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits224; } }
public static class Groestl256HashSizeExtensions { extension(Groestl256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Groestl384HashSizeExtensions { extension(Groestl384) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits384; } }
public static class Groestl512HashSizeExtensions { extension(Groestl512) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class Haraka256HashSizeExtensions { extension(Haraka256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Haraka512HashSizeExtensions { extension(Haraka512) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class HavalHashSizeExtensions { extension(Haval) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits128To256; } }
public static class IsapHashSizeExtensions { extension(IsapHash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Sha3HashSizeExtensions { extension(Sha3) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits224To512; } }
public static class Md2HashSizeExtensions { extension(Md2) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits128; } }
public static class Md4HashSizeExtensions { extension(Md4) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits128; } }
public static class Sm3HashSizeExtensions { extension(Sm3) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Lsh224HashSizeExtensions { extension(Lsh224) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits224; } }
public static class Lsh256HashSizeExtensions { extension(Lsh256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Lsh384HashSizeExtensions { extension(Lsh384) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits384; } }
public static class Lsh512HashSizeExtensions { extension(Lsh512) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class Lsh512_256HashSizeExtensions { extension(Lsh512_256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Luffa224HashSizeExtensions { extension(Luffa224) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits224; } }
public static class Luffa256HashSizeExtensions { extension(Luffa256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Luffa384HashSizeExtensions { extension(Luffa384) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits384; } }
public static class Luffa512HashSizeExtensions { extension(Luffa512) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class PanamaLEHashSizeExtensions { extension(PanamaLE) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class PanamaBEHashSizeExtensions { extension(PanamaBE) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class PhotonBeetleHashSizeExtensions { extension(PhotonBeetleHash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class SparkleHashSizeExtensions { extension(SparkleHash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class XxHashHashSizeExtensions { extension(XxHash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits32And64; } }
public static class Ripemd128HashSizeExtensions { extension(Ripemd128) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits128; } }
public static class Ripemd160HashSizeExtensions { extension(Ripemd160) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits160; } }
public static class Ripemd256HashSizeExtensions { extension(Ripemd256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Ripemd320HashSizeExtensions { extension(Ripemd320) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits320; } }
public static class Shabal192HashSizeExtensions { extension(Shabal192) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits192; } }
public static class Shabal224HashSizeExtensions { extension(Shabal224) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits224; } }
public static class Shabal256HashSizeExtensions { extension(Shabal256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Shabal384HashSizeExtensions { extension(Shabal384) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits384; } }
public static class Shabal512HashSizeExtensions { extension(Shabal512) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class Skein512HashSizeExtensions { extension(Skein512) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class Streebog256HashSizeExtensions { extension(Streebog256) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class Streebog512HashSizeExtensions { extension(Streebog512) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class SubterraneanHashSizeExtensions { extension(SubterraneanHash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class WhirlpoolHashSizeExtensions { extension(Whirlpool) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits512; } }
public static class XoodyakHashSizeExtensions { extension(XoodyakHash) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits256; } }
public static class XxHash3HashSizeExtensions { extension(XxHash3) { public static IReadOnlyList<HashSizeRange> SupportedHashSizes => HashSizeSets.Bits64And128; } }
