<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FileFormat.BinaryII</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\FileFormat.Squeeze\FileFormat.Squeeze.csproj" />
  </ItemGroup>
</Project>
