#pragma warning disable CS1591
using Compression.Lib;
using Compression.Registry;

namespace Compression.Tests.Office;

/// <summary>
/// Every registered descriptor has to be reachable through <see cref="FormatDetector.Format"/>.
/// </summary>
/// <remarks>
/// <para>
/// The <c>Format</c> enum is generated by <c>Compression.Registry.Generator</c> from each
/// descriptor's <em>class name</em> minus a <c>FormatDescriptor</c> suffix -- it never reads the
/// descriptor's own <c>Id</c>. A class whose name does not produce its Id therefore lands in the
/// enum under some other spelling, and <c>Enum.TryParse&lt;Format&gt;(desc.Id)</c> in
/// <c>EnsureRegistryMapped</c> fails for it. The descriptor is then silently dropped from every
/// one of the detector's lookup tables: it can be constructed and it answers
/// <c>FormatRegistry.GetById</c>, but no extension, no signature and no explicit format
/// selection will ever reach it.
/// </para>
/// <para>
/// That is how three CFB/OPC descriptors shipped dead: the registry accepted them and their
/// detection tests were compiled out, so nothing noticed. This test is the cheap guard. The
/// quarantine below records the descriptors that were already unreachable before it existed;
/// it fails on a new one, and it fails on a stale entry so a fix cannot leave the list lying.
/// </para>
/// </remarks>
[TestFixture]
public sealed class DescriptorReachabilityTests {

  /// <summary>
  /// Pre-existing class-name/Id mismatches. Each needs its class renamed to
  /// <c>&lt;Id&gt;FormatDescriptor</c> (or its Id corrected) and its entry removed here.
  /// </summary>
  private static readonly string[] KnownUnreachableIds = [
    "AcronisTib",   // AcronisFormatDescriptor
    "EaseUsPbd",    // EaseUsFormatDescriptor
    "FlacArchive",  // FlacArchiveDescriptor
    "JpegArchive",  // JpegArchiveDescriptor
    "xDisk",        // XDiskFormatDescriptor  -- casing only
    "xMash",        // XMashFormatDescriptor  -- casing only
  ];

  [SetUp]
  public void SetUp() => FormatRegistration.EnsureInitialized();

  [Test]
  public void EveryRegisteredDescriptorIsReachableThroughTheFormatEnum() {
    var unreachable = FormatRegistry.All
      .Where(static descriptor => !Enum.TryParse<FormatDetector.Format>(descriptor.Id, out _))
      .Select(static descriptor => $"{descriptor.Id} ({descriptor.GetType().Name})")
      .OrderBy(static text => text, StringComparer.Ordinal)
      .ToArray();

    var known = new HashSet<string>(KnownUnreachableIds, StringComparer.Ordinal);
    var regressions = unreachable.Where(text => !known.Contains(text[..text.IndexOf(' ')])).ToArray();
    var stale = known
      .Where(id => unreachable.All(text => text[..text.IndexOf(' ')] != id))
      .OrderBy(static id => id, StringComparer.Ordinal)
      .ToArray();

    Assert.Multiple(() => {
      Assert.That(regressions, Is.Empty,
        "these descriptors are registered but cannot be reached by extension, signature or explicit "
        + "format selection, because the generated Format enum does not carry their Id; rename the "
        + "class to <Id>FormatDescriptor");
      Assert.That(stale, Is.Empty,
        "these KnownUnreachableIds entries are now reachable -- remove them so the fix stays enforced");
    });
  }

  /// <summary>The three CFB/OPC views specifically, since they are what this branch adds.</summary>
  [TestCase("CompoundFileBinary")]
  [TestCase("LegacyOfficeCompoundFile")]
  [TestCase("OfficeOpenXml")]
  public void TheCompoundFileAndOpcViewsAreReachable(string id) {
    Assert.Multiple(() => {
      Assert.That(FormatRegistry.GetById(id), Is.Not.Null);
      Assert.That(Enum.TryParse<FormatDetector.Format>(id, out var format), Is.True);
      Assert.That(format.ToString(), Is.EqualTo(id));
    });
  }
}
