<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FileFormat.BitRock</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Compression.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\FileFormat.Tar\FileFormat.Tar.csproj" />
  </ItemGroup>
</Project>
