<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FileFormat.AcronisTibx</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Core\Hawkynt.Compression.Core.csproj" />
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\FileFormat.Acronis\FileFormat.Acronis.csproj" />
  </ItemGroup>

</Project>
