<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FileSystem.Msa</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Core\Hawkynt.Compression.Core.csproj" />
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\FileSystem.Fat\FileSystem.Fat.csproj" />
  </ItemGroup>
</Project>
