<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Codec.TrackerXmIt</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Compression.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Codec.Pcm\Codec.Pcm.csproj" />
  </ItemGroup>

</Project>
