<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FileSystem.Nwfs386</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\FileSystem.Nwfs\FileSystem.Nwfs.csproj" />
  </ItemGroup>

</Project>
