<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FileFormat.Wave64</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Core\Hawkynt.Compression.Core.csproj" />
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Pcm\Codec.Pcm.csproj" />
    <ProjectReference Include="..\FileFormat.Wav\FileFormat.Wav.csproj" />
  </ItemGroup>

</Project>
