<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FileFormat.RealMedia</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Pcm\Codec.Pcm.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Ra144\Codec.Ra144.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Cook\Codec.Cook.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Atrac3\Codec.Atrac3.csproj" />
  </ItemGroup>

</Project>
