using System.IO.Compression;
using Compression.Registry;
using FileFormat.Swm;
using FileFormat.Wim;

namespace Compression.Tests.Swm;

/// <summary>
/// A split set written by wimlib, read by us. The reverse direction (our set, read by wimlib) is
/// <see cref="SwmExternalConformanceTests"/>.
/// </summary>
[TestFixture]
public sealed class SwmReferenceTests {
  // wimlib-imagex 1.14.4 (Ubuntu 24.04 wimtools 1.14.4-1.1build2):
  //   src/a.bin, src/c.bin, src/sub/b.bin = 7000 x (97 x letter + "\n"), letters A, C, B; src/s.txt = "small\n"
  //   wimlib-imagex capture src ref.wim --compress=none
  //   wimlib-imagex split ref.wim ref.swm 1        -> ref.swm, ref2.swm, ref3.swm
  // Stored gzip-compressed and base64-encoded.
  private const string Part1Gz =
    "H4sIAAAAAAAC/+3SXWiWVRwA8P87IWQgRN4UFUUUXQTuw2Vab+Lalo72IdvSCXWhWeSNhK02WRdLCAaKNxV1GYRUV0UXWdQqu6muWoRoxSKELBzdRGAQZP89" +
    "7/vK9u4jFyRd/A6c55zzPx+/53z0Du7u7o2I6cyxrhSTUUnjr/54/QePzGx799Hn1h/7rv1kKdZEKeP7K90Nw+ONRaXajsY1lfhH1Xi1fdVT+3+dGgkEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCIT/j7A2KunJanlt5kuZxmLpdPji" +
    "1IkzO2dKM+e/LcpaO1aZautPVL3lxu15q7L+2tkzRVlrv/Lm1L1f3njf49037//03POf3/nT6K976+c2xt7YEPviQBxctVvb14HTZxfsc+SHT0rbDnc+e3Lo" +
    "/B3N369/+/aLH/622H1sWTcarsytP9/JP/smT+06cur40Rvef+O9C3+Mrtv41WL36XRH0hq5HHuq7l6HG1Y+5/rySu7ymnSfyf3+m/t9Yrri1Jcf3/TiLb9v" +
    "uHD0pRMTrx2b3XWu5euJ1xfvd9+ic66ls5V9NkyMNc5vRynmtnTdXd+0He/95efxlz974eAXs0emOg6NvTNaGTldXaHWrsxY6r1d+qscu6M7emNrlIuyPbZH" +
    "V9ya9b7ozNpw3B+3RUvmuRF92d+b0a15XofyjZSjaV6snDO6YyA6oj8ezvhQxlqLMYvj5XgwYz05b360rRi9VE85v/2Z27PngdiTta4YLNZvjrtjc36bY1Mx" +
    "e+lx5diRsYH8k55ibw8t6G0uZq40opx/M5D19ox0p9BXlLV978j69vzuLFYYKlYcy9ySq3Xm/zXn956qUT+ynF5/3sLCuR2xMWdsylhrGl3F3Ppxc7GV/qon" +
    "44MZ6c2euRuYO9eOq7yDzXmKbblK67I7WM1fNs17o//0JrakuqXqLvcmmi6//r8BTUS7tMZ+CgA=";
  private const string Part2Gz =
    "H4sIAAAAAAAC/+3SzW9MURgH4HfaxGISKxt2Iqw72qpKLjGmxURnKm19JSyEJRtEKyzEQpoQa/+BJbFQYiH9C3RNiJVFlzYkErxzZyqtz1gQi+ck98y5v/Oe" +
    "85w797amjzVbEbGUV6yvxHx029W7bzY+Oflq78NT1zbcflFf6Iv+qGR+tjvdd3OuWg5691Ht7+bLvbx3/89b42+3KoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgfD/CBfPnz53rvpgthqdthTdtnLfF5XsL71+Vtl7ZezywszbbbWX" +
    "G+5vff/03bpe5fW5buXKfXfF/Mf2/OLRG4t3bm16fO/R8ofZ9UPPP38q4lg0oxV7oih/63EgxmNzjtsxlqPjsTu2xPa8OhXtnG9luicuxoU4k8nAqqzIFc2Y" +
    "ikZMxpHMZzIbLGu+z4vYn9lErludDpfVP5opsp/Mq54z++JEjsZjuty/FjtiNPtajJSrf1xXxMHMpvIkE+WzHVozWytX/qqiyNNM5bieSTOFdvm78twHc3wg" +
    "+8PlDjPljnN5bc/dxvJ8tex39oxvK4v0JvMtrF3biKFcMZLZYBrj5dpv6zrZr041kfl0Jq2c6byBzv/a+MdPMJr/4nDuMvjTJ/iTUw6s+kZ/903sSnVXz/3Z" +
    "NzHw9ev/AqSTc+H0ewoA";
  private const string Part3Gz =
    "H4sIAAAAAAAC/+3SPWtTURgH8CdmCzi5OAiKH8CmsdYWrsW0jW2waaSpVkEnv4EOFnToKNhNB0dB3KWLuPgZ6ioI4qirs/rkJpW0thUHi8PvwDn33P95+Z37" +
    "0umttTsRsZ01jlficQzKw+efTr69/fHy1p1HJzY/NN9UoxqVzBuD4WMb67WyM7yPWnWQbw3z4f2Rl9l/XWoEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC" +
    "gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE" +
    "AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI" +
    "BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ" +
    "CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg" +
    "EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA" +
    "IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB" +
    "QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCATC/yO8flCLftmOQdm5r0Yl23ennp7+du7Lk2evNl5sfr3xefz9xssf34tY" +
    "i3Z0YiaK8tqMhWjFmewvx3z2bsalOBvjWfszlnO8k+lM3I97cTeTsZGsyBXtWIm56Mb1zFcza5Rzfs+LuJLZUq4bTSfK2fuNFNl2szZzZDZuZa8VvXL/elyI" +
    "qWzrMVmu3n9eEYuZreRJlspnu7prtF6uPGxGkadZyX4zk3YKy+V157kXs7+Q7bVyh9Vyx/Ws47nbfJ6vnu3FobF3ZpFeN7/C7rVzcT5XTGbWSKNVrt07r58d" +
    "dqqlzHuZdHKk/wX673XuiJ9gKt/iRO7SOPAJ/uaUYyP/6J/+ielUp4fuQf/E2K+//yeIcBixvHsKAA==";

  private static byte[] Gunzip(string b64) {
    using var gz = new GZipStream(new MemoryStream(Convert.FromBase64String(b64)), CompressionMode.Decompress);
    using var ms = new MemoryStream();
    gz.CopyTo(ms);
    return ms.ToArray();
  }

  private static byte[] Payload(char letter) {
    var line = new string(letter, 97) + "\n";
    return System.Text.Encoding.ASCII.GetBytes(string.Concat(Enumerable.Repeat(line, 7000)));
  }

  [Test]
  public void WimlibSet_GivenAllParts_WhenRead_ThenEveryFileMatches() {
    var parts = new[] { Gunzip(Part1Gz), Gunzip(Part2Gz), Gunzip(Part3Gz) };
    // Supplied out of order on purpose: parts are matched by their header, not their position.
    using var reader = new WimReader(new MemoryStream(parts[0]), [new MemoryStream(parts[2]), new MemoryStream(parts[1])]);
    Assert.That(reader.Header.TotalParts, Is.EqualTo(3));
    var named = reader.GetNamedFiles().ToDictionary(f => f.FileName.Replace('\\', '/'));
    Assert.That(named.Keys, Is.EquivalentTo(new[] { "a.bin", "c.bin", "s.txt", "sub/b.bin" }));
    Assert.That(reader.ReadResource(named["a.bin"].ResourceIndex), Is.EqualTo(Payload('A')));
    Assert.That(reader.ReadResource(named["sub/b.bin"].ResourceIndex), Is.EqualTo(Payload('B')));
    Assert.That(reader.ReadResource(named["c.bin"].ResourceIndex), Is.EqualTo(Payload('C')));
    Assert.That(reader.ReadResource(named["s.txt"].ResourceIndex), Is.EqualTo("small\n"u8.ToArray()));
  }

  [Test]
  public void WimlibSet_GivenFilesOnDisk_WhenExtractedThroughDescriptor_ThenSiblingsAreLoaded() {
    var dir = Path.Combine(Path.GetTempPath(), "swm_ref_" + Guid.NewGuid().ToString("N"));
    Directory.CreateDirectory(dir);
    try {
      File.WriteAllBytes(Path.Combine(dir, "ref.swm"), Gunzip(Part1Gz));
      File.WriteAllBytes(Path.Combine(dir, "ref2.swm"), Gunzip(Part2Gz));
      File.WriteAllBytes(Path.Combine(dir, "ref3.swm"), Gunzip(Part3Gz));
      var output = Path.Combine(dir, "out");
      using (var first = File.OpenRead(Path.Combine(dir, "ref.swm"))) {
        Assert.That(new SwmFormatDescriptor().List(first, null).Select(e => e.OriginalSize).Sum(), Is.EqualTo(3 * 686000 + 6));
        first.Position = 0;
        new SwmFormatDescriptor().Extract(first, output, null, null);
      }
      Assert.That(File.ReadAllBytes(Path.Combine(output, "c.bin")), Is.EqualTo(Payload('C')));
    } finally {
      Directory.Delete(dir, true);
    }
  }

  [Test]
  public void OurSplit_GivenWimlibInput_WhenResplit_ThenPartLayoutMatchesWimlib() {
    // Same files, same part size: our split must place resources exactly where wimlib did.
    var files = new List<(string, byte[])> { ("a.bin", Payload('A')), ("sub/b.bin", Payload('B')), ("s.txt", "small\n"u8.ToArray()), ("c.bin", Payload('C')) };
    var ours = WimWriter.CreateSplit(1 << 20, files, WimConstants.CompressionNone);
    var theirs = new[] { Gunzip(Part1Gz), Gunzip(Part2Gz), Gunzip(Part3Gz) };
    Assert.That(ours, Has.Length.EqualTo(theirs.Length));
    for (var i = 0; i < ours.Length; ++i) {
      var a = WimHeader.Read(new MemoryStream(ours[i]));
      var b = WimHeader.Read(new MemoryStream(theirs[i]));
      Assert.That((a.PartNumber, a.TotalParts, a.WimFlags & WimConstants.FlagSpanned), Is.EqualTo((b.PartNumber, b.TotalParts, b.WimFlags & WimConstants.FlagSpanned)), $"part {i + 1}");
      Assert.That(a.OffsetTableResource!.CompressedSize, Is.EqualTo(b.OffsetTableResource!.CompressedSize), $"entries in part {i + 1}");
    }
  }
}
