<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FileFormat.Matroska</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Compression.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Pcm\Codec.Pcm.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Aac\Codec.Aac.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Mp3\Codec.Mp3.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Ac3\Codec.Ac3.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Flac\Codec.Flac.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Vorbis\Codec.Vorbis.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Opus\Codec.Opus.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.MsAdpcm\Codec.MsAdpcm.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.ImaAdpcm\Codec.ImaAdpcm.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.ALaw\Codec.ALaw.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.MuLaw\Codec.MuLaw.csproj" />
  </ItemGroup>

</Project>
