<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FileFormat.Iti</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
    <ProjectReference Include="..\..\Codecs\Codec.Pcm\Codec.Pcm.csproj" />
    <ProjectReference Include="..\FileFormat.Its\FileFormat.Its.csproj" />
  </ItemGroup>

</Project>
