#pragma warning disable CS1591
using Codec.Alac;

namespace Compression.Tests.Codecs.Alac;

/// <summary>
/// Conformance tests against ALAC streams produced by a foreign encoder (libavcodec).
/// A round trip through our own encoder only proves that our two halves agree with each
/// other; these fixtures are the independent check. ALAC is lossless, so the only
/// acceptable result is byte-for-byte equality with the PCM the foreign encoder was fed.
/// <para>
/// Each fixture is the concatenated raw ALAC frame data plus the 24-byte magic cookie
/// lifted out of an MP4 the reference encoder wrote. The source PCM is regenerated here
/// with integer-only arithmetic, so it is reproducible on any platform and the expected
/// values never come from our own decoder.
/// </para>
/// </summary>
[TestFixture]
public class AlacForeignStreamTests {

  // ── Fixtures: raw ALAC frames + magic cookie, produced by libavcodec ─────────

  // Tone16Stereo44100: 2 ch, 16-bit, 44100 Hz, 5000 samples, 2 frames
  private const string Tone16Stereo44100Cookie =
    "AAAQAAAQKAoOAgAAAABABAAViIAAAKxE";
  private const string Tone16Stereo44100Frames =
    "IAAAAAAPCAGz/3n/6f/sDwgB7/8SAAn/+f844p9p+J976wmglAcAUAYDAIgEAIBQJB4AgPBIAwLDgEBoSCIaCYUA4IJjAmLBYkEi" +
    "AKDDAhpQWW/4DnP+CeHZz6DCUMAqCQKChQeDAAQJBBQkAcTCBhYoKAY04MlYY9ItAly2FAj3F/4HHPDaYwuo2IiwWJBwYYEHABhA" +
    "RKA4ZS5y5y5hoHSEI+uKdsbYHKr/gOg/4J2diOoQJoxB4OB13Pk4LCQUIAgsUDABDyQUAGEENSFHQXKVKTMVdMRDUQf/wOPdkgiP" +
    "LHUpAwMCDBxJYINJDSgkMceMOgiIGUmciqRBHzxRpYmN8P+A5b/gnX285gktjkHAwVEBUGAAQWHBwAgsQOIiiogIswcZNQtYkoE0" +
    "5U2gJsq4f8DlXcoMkyBlHQ0EBRQ8MDCCjogaS4oEkUCjVCVD0BwiTj2jWDKZEUp0/8Bun/BQbvppB8xBYAGCIQBBYoGhgGHGFRhE" +
    "MCAHoEmDgFKHNOJWNYuCUKSOdbP+ByDwWVH7KegoAEDywscJHBRSEELUHDKXICFHKLHTFK+dLjmfG1xx/8Bv3/BPbuZzCBIEwRCg" +
    "QIiQKEjwKCAhpASSDhxhUMEKDhf8AmsiLEgClKoNnGhDHoBjZ/wOaeFxpTjS2OgQmCAQUWcDjiIYEHAGNMHAKUaUiMVSRxpcM7Jk" +
    "DdR/wHAf8E6+8oAWDgSA4EjQECg4QBBIgHCjCoYMPKBQYwZipiJS5BBZx9KUOkU9AB/wOReGxhplzGRgYMBhAUQEDgwwMURIDMVQ" +
    "TEGJGMPQBGuOJP/AFstNQFUn/gOM/4J6eA24CEERgsBAQGEjAGHCoYRDBSBMEGEjhqhpQoxpQ4RrB5CmsohEY7D/8Dl3jM2XWU5B" +
    "QcKDwwImaImB5YeUCjmHkBjCGoDiNja4JJ3ztlWpM//Ac5/wTr7+bwaTRcGgYGiAOCBYkHiAkUFABCxwUAKUmQIWgSYWoOGQiVHG" +
    "pY5S/8DwWStpSvm4aCAwcKIChAw0oJIKNCCHERUJMJjW5cDifK2VbCjQT/gOW/4Jv+DYdBagKQgAgYRGhEUACIYFCCxBAmGCDSgp" +
    "MBbQiKxKRJg4rJDDdQqSH/A5x5jRlWOKp6Ch4YBEQBxUgRBBh5Q1Qk4kY40BRYhkoIQHsB8b53/8Bv3/BODxrN4mRw6CwaJBocDz" +
    "gKEhIGAgYAUIGGjg4AhZg4Q45iqCIQgbBbkuKL/gck9ryFxaxcCCRINEhIgUJCBRQ0MCDFGFKLCELULYuNtL52wXKmVav+A5j/gm" +
    "94hoEARBKDQcADRAJCAwRCAw0UDBCRA4iEDKPEAIOAUYAIlCCLYDWF/4HHvX8vgjmNhYkEigSMHmiJYSUIkqDzjBSbHhgg4hpg4Z" +
    "ypSJABoIthS/8Bwn/BNbxnXqYOBOCAEDQ4HBhMWCQwHCjCoYILJCywtJFg9AcQsoJUxkx4jLjijD/gcu9pzWLSZhJQoLBAUIBjCp" +
    "AiEACiAxqxZAxCKAohqT4DTORLEuONn/AdF/wTP8T1WgEcQAQDhMMEQYGCQ4NFhIgkZJGRQ8QAISQgv9QxRwgYYs4lAlyUMf/wOM" +
    "e56rWHMpChEGAAAYWOBgwgIOCHpCilMpLlGjAHY8yIp1ojoZEqb/gOE/4JueSabVCGJAaBwOAAAAIFBQoTCAg4QWQFkhIYokIQcU" +
    "xUgY+C41uKdAly/8DlXvOl0hhOwcAChQqFDwwAMQEHkAoZSJSJAAyjxhIo1zvlL+v/gElststh/8By3/BNDxncMKoIZAUCAQJDgM" +
    "FDBEGBwwmOIhgYoqGDBxTkRgyl0lTEwgETG+NM7/+Bw71vQ6NNHkxDQQCAwUIEEjAYUQAAAAMYYs4cMxUpaCqmZEp5hJM7/gOi/4" +
    "JkePatbiGIQOBYsGhweKAYKEAAw0YJFAiYYINSPUDFGITSFDIAj4DOppDf8Dl3uOe7rZIoYhAOFB4QEjAIOGGjBpgiaFnFpFpGrI" +
    "sFnBk3gVAlwbKv/gN+/4JveYatWR8JAWAAwPBgMIBAkMAw4wqKHiiowuKLGCNUNOHAESUcjYFOgam/8Dinvefz5vKwYCBwUIBih4" +
    "QEHChgQlZFQ1IcMgUw0QBNUD6WqORag/4DmP+CaXkGhTYligNAAGBQoNVcgRhEbGQMQKggAQBEsLGCWDUj0AxTERAFU9lDJnf8Dm" +
    "Xr94XYstkIkEhgaLDRwkgLGAwQ0kOSsAM5cw0gMCnskdEYaBkMP/gOW/4Jq+TZlJR4HAHChMCBg0YCwoARIADRgcEFCilyjxgiTA" +
    "xyixCSiExgIudf/A4l6LMlOWPJiKiAiDBxg8MCDgBBY4lD8kXZjpEHrHpBlvBjBqkhYyJkn/Ach/wTl8xwqAzYOAgIigOBgwKFBY" +
    "IDBAg4McTEBRR4ChzzgxRgAI2VajiSxcC/8DjnsNaN3UdBQkcABBYoWYFkA4k4CLULOHCPWLKDCXK9wyLQ6JVEKP+A4j/gnL5Xjk" +
    "PmAjB4AFCIUIhAIEhA4iAOGgChYgKUqMQWRq/8AkMAfCDOXEEJULIQTG/4HGvU6Qsy5jKQMKEQYGGjgoUMIIliJABpByIEERhTDz" +
    "DIZcZTskdQj/gOI/4JoeYY7Gx+FQGDRILEA0UCRAJHAESQcGKJhgxqBKBaRZw4QoZiumZIJD51/8DiHnscNZs4mYWBAgGDBAhIwO" +
    "CDhj0jUizhSXBQiFoQNkymuiD/gCyB1x/+A4b/gnT5vhcel4hCABAYUHhAOGCIUGgChoIMPJCSQUtgI1Ak4clwBNZ1NIRsb6f+By" +
    "7324JraIhZAChQqKJhgQkYHABDjkFQgDElBhjFdQgRyHTWBWPJ/wHJf8E2/N8ZgRCEwPBQKAAwwPBgINHBQYoeEBBQgswkwUAABl" +
    "IseCDLYlCokC/4HJvgl6nUNXVtHIQoPAw4AODDBRhMYVHJlGjAAEesagSRiSHY91Clj/4DfP+CaHpGfzUaiAEgaMB4oEhwANCBAy" +
    "ICBwoYEHCHrFoEmChHrHrFoLcC0MkU//gcW+CW5zlTeWgoAJFgYeSChxhEMIGiDl0FRghQzlyACbA4DQRaikP/wHLf8EyfSs5lxA" +
    "DAACRwCCQ4DAA8yCho0SDhRAMAUJCACLKASQciEMuNsb5TlVN/wOKfIsbdXkpCAcQEwwyKHhhA8cFBDUBxRgBCinNmImEcqlkGIh" +
    "SPj/4DmP+CZnpGXQ8mioNgQEAwaHBokEhwWOBiTgMAUNEBCTC1CTiRihy0IEcqBNc+n/gcq+WY29s4iDhAQGhwkkLLDSgsUHBGsc" +
    "z/gE1nRJkKHKTOXKJDUJIOXOiMRf/Ab9/wTK9S0qdjUPggCRIJFA0OAB4kDgh5giSBhxRkYeUmYmMGcucmIIlwRRnAsP+BzD5Vib" +
    "XHlkdBwYPFAkQIBCyQ8gFBhhiSgxykzDxBGwbAaZwM1RwJ/wHNf8EwPTNLk5DDgFBUOEQIECxYPEhEwPJBQYQAEDDIFICJKCV+0U" +
    "w8gakekOIuC/+Bwz5dmMCgReAAAAIJHDyAcIJIAxZoMWUSsagWkOGUmqRTyANAkztR/wHCf8E0fUdNjpEEYQBAPFg8QCRALEAcKI" +
    "BhAAooSCELKFAMaYSoSI6YwhjMMxD/8Dj3yjLXFxIwsYDRAJGAwowmGABjCZSpyowhKRJxJgo1TQmVVHV83/AJXjL/8B1n/BK/zX" +
    "SZyVhaGwFAwMEhQKAAgkOCyQ0oJGBQQscDJeAGQAAZRpCwmVIYAEf/gcc+PYW4yBvJwQDBQYAFCCBIoGDAHGjBjAELWPSJIU8QGX" +
    "A51RIAP+A47/gmB6lqMlHwVAIJFAUHChMODwIFFCxAMAYLAGHjCFmBilLoGiDQI5SIa5M//A5N8iwNFkC/XCksHBQHCzgIOEFkCJ" +
    "YWQFoFsIoFqFpChgU90xCueYqv+A6L/gmN6VkMPngaBwHCAMIAAwSFB5AOAECiywAYaQciAocsZA8BUSAAy1JjbH/wOVfKsHYWsT" +
    "Bw4XDhkUNDAxxUYXGExyYwAjVBxSAjaXwKJ87YHKgC/8BwH/BND1LNIgRhOEgSBAsUBwUKE1vQmIRIwYeSChRhMQAHONEDKVOREC" +
    "NWNlfApYf8DmXxizJMUXxcJDgcDBBA4cULDAxQ0ByYgQoowYwELMx5kRQB7ijN/wHIf8Ex/U84hpXHAZAgABhwyHCoMDB5ISWHkh" +
    "5AAaQLUHJgHIGPYRULUJUUDwmd/wOWfMLofxxZIRQLDAcCGlCJIGFBBBKh5gYPyw5byBJgoZiJSZBHABNh/wHLf8EyfUsbh83DAJ" +
    "A4GDAoQDBYYDgwgAUgVDBA4AQ5LQYgZARMcUBlIIZVTKb/wOOfHLYbu5SFC4kLhhUcVCAgCJYeSFDGERSFCPSDHMSSUolsGUhDh/" +
    "wHKf8Ez/V8jjs5DQDBAIGhwAPEgcJMAAAhY4SSFkj1j0iRjjRN//gEz4puUWgWseoOOl/wObfJK4SxxTOwsCAgMAJMBRxMcVEAAy" +
    "AhwxABFmCibBcAWgwgewof8Bx3/BL32XQINSBKDgGADhMIAxIZBgQeUDhxREURDBD1kWEViyhRBwHY0w0AMxv+Byb59fjWRNIyIg" +
    "QMHigsUDABiiYwiKRKPEELQLKCVMaDEgyRAESr/gDA/4Dpv+CaPwlZoTGAOAYJFgIFAA4UFgAYIJJDSAcKKIiAhxSjRAwghyNglR" +
    "yNgmC/+BxT6JjqK7nIIEiweIBQ4oiICjiIQGUeUmQMegKS0EmCXFGyqEhCFH/wHIf8Ey/atTiErCgHCoUHgQQFhgOAAAAABhYoKA" +
    "CNQJODFCIPQDKYhzoIkzEm/4HIvs2arrWOtugLgWJgYKDBxg8URHEQwUUaEIOGUeMGYeIRxoAS3HAn/Acx/wS09l2KQEAPgIAAoQ" +
    "BAoGIDYcIgDBoQKOJhAw04MAYQQYYgbHkEuNMFuKT/gcu+jY2hyhjHQkAFCIQFFCQZAGFCBAxRACFoFlBHmKgBoE1xxqWBv+A47/" +
    "gl17br0aH4UB4ChAEBhIsCAoKFEd2GUKCw4mEBDSA4ZSJiZRIaBJhzNUUan/8Din1zWVt5IxcOFQwZDiowuQJihoAr/nHBN1N7N3" +
    "bqCEAwBwDAIASAgBwLgUB4HAuAwCASBgDAoKCoMC4UDYQFwgDCg8CBg0UDgCTwMEGFliagoYQx//AyagGAc0HgsIHiB4gWDIBQh5" +
    "QSpRYghJhahSGIUqHmIszGsiMOuuWpI5J/wMeI6KdvzYYOGHkA4cQIKOQGQESYKK6hlDJEEbK1hQM9gwCz3n/wBU++SYpv+BjtAS" +
    "j5OKBgxE0PHAwogAB0ERAj2C0DUDkWoo1RKmdMqQxmwbGC0MzMP+BjIrKV9AvGiBYIQZDCzByAGlCkLjqAIdR1NcUj2FAbpiI3Ni" +
    "ozylca/8DI5kYOJVIYCESgcKOLhgCDgLeFKJAQJ8ZxFTKh8pV3jIL/gDA4zEynnGCjh/wMaF5+gxx8mKHhAAwkMSXMRAkmEQWYKG" +
    "Qy55KXwOB0GOu0bJAYsmtUW/4GSSQ6JSMGgDiBY4KGIjiUjUixEmUESjRZVwOxcFuKeMajjQLOJMYrnX/gZEQUknHLw4waKKii44" +
    "iQAItZFY1A04tYtxyushIL/gDBwxWwiVJlknWxcEqT/wMfqTMGTKgUfAABCSQkYGOMMWcScSoaYORtL42wXKthU1gRJo7pZDDQfL" +
    "/gZETUsNx8U5CGQYweAKFg1jzhxhiFxDThQPGAhpnPAy4HExIn4Wbrd6/8DFqYsDk/FkBZ4AAOMIiACnIgMNIJeHMmZND/gDOlhm" +
    "CFoEuXG+N8ClIig9IE/4GRGGFErCMiBo4GHEACBZBAxqh6RIxyZyIhoqVqXS9gqlHkrknWyKtLjjF/wMcpCYH5aXOFgAQ8gLJBwR" +
    "x4QQYYCCRCmAi0EeOd8sk8kp3LMg49HzvYv/gYkRYQJ2ycEHBgggBMsPaRSPULOLQJ/SoEJjrCiDGrTTtg2OSd8sVNE4LMx//Ax+" +
    "nRUEej4ULKBwoQIDEmBDThQDnKmHhBuiMQq8S7SoRJOlS53ylTSVSRf8DGR2vhV5ELwBJIaMDjhY4k4cgMItJFQ1IuNailQkHREE" +
    "dAWyleV3vbS3/Ax+vSEgaFAgaSHkA4YiSFrIsfouBssIMMQMhEw0xEgEB6hlU1E0JESKOCM/+BipZkQzAkUmIHjgoIaQFjhxD0gy" +
    "XByAgx1SKegj53xvjKm0E1minaxdMUv/AxSmPwblqNMEDkgQImGABDjGGiBFnDlCjEQolsTGtj5VuOoZ8gjVT2pf/gZAXZ0aqpqH" +
    "ECxAoeI2y0GXCCUDTAwwILmFiBoaYAGiR0RjJMpYgEto8/+Biton5NBUIoHGEQQYAmQDhnLoLoIhCFqIsI0vNCRjS1tgdOI5BqSI" +
    "Vsscf8DHzPLB+GKYyLADBh44ASKHQPQLWNKLQJWTQOoIp2qOZzTAe08BoWY2Bf8DFbZNxZ6hTW/YAhQ42YFlgxMweQKMaYAtA1AS" +
    "p0ykgqKEghDKpYRZiplL/gYoc68bt5iEEkBI4aUCgwwpyYghKhpBRZ1BiuiQUxkoUkCEVLZW54ypkf/AxWxTcZlrkaEhBEMCBhRQ" +
    "8GoKKEMWQAUMwCWoFuKRrlwSw8IpTkrqzdSf+BjBGw8eRx8EKMhhpYqWDhiCxBRBgxQhm0zQGm1s4ipnI+VrCgNWrHokeX/AxW6X" +
    "EkgqAKAxRUULCBhYoSkakOKYmMKk2YSBjLQxJCmI2d8bXFA2AOP+Bjpjrg/ElcnCAi5ImCBBxQUdgdYAQ4hh4wzCTG1yUADUEkML" +
    "HC4X/gC0yF1P/4GSWinhsTZDICFBRogEPCBRBIw5wg5QE1k1i4LYuB3LMxoQmMAj5NjfGuP/gY+f8LLV8TBRAMMGDhSBkcREENWN" +
    "IQXSVIAVAAN1BDHGqSFkIiIeokyojf8DGLJWxGIrRAHLAAABBo4A84B6hJhqAZbA9ZRwBaigZsb4y/8AWecV00dkHln/4GPlWwE0" +
    "iZzkPABADxwkkPJBzBSVgAFINGDQ9DTDQ9UTKoNIA1JCNa9L/8DGLFjAJJWI6DgoAUIMTog4wWMKMESoWUKAA2TMmhMqRjVTEEEU" +
    "ZysmjqdJ/wMZKN+CIYtk4YSSHjgoAIeUPSLQPULOLQCVGKpYiJQH/AGJHTnikAdjUHdIY03/AyWxYENxFwJBAOGHExhEEGEiizgw" +
    "xgi1kShSFTKWFUdDDllbAo0SMeYAz/8DGDDlIrCEsfCgxRMIGGlh5Q0hBdJcxco0xUYIYzDhZHZLQypTVPCFEdSns/4GJUrEA2Ks" +
    "BkGFDwQIGHLCTAAxAzkQinVgizCk/4Ar6CVokYcxoMeQj5VwSZkTP+BkhhzEzgSeNhwkYALFACRgtA1Acwcos4coeOKVJkJBUUJB" +
    "GSooqXetJin/AyOwaYNNxINBh5AeWCiTgssINMAmsSUGKcyc0RGuOJLkuXXRa+DYyjVVHN/wMUKePgI4rloUMLFBxwssTLDzCUDV" +
    "jzi/qWRY5yYwQ4Yg3SGE2mKdrmwGdBm/8DH6tmATBUg2BEDIweMGgxwkgSQGAA6wpzKSpixDIIYHjA842TKehbGwT/gY+ZdlKWMT" +
    "BRhEMCEkhpIaODHKRMTECLUJMCic5XUMeqQRDkirkrkgcRSk/4GOT7QgOGqhcOEGRBswDBBh5Ysb8hLDsNhAPOHGJMHFdEgTZ4p2" +
    "yvguVahlQb/gY+S9TI3c3IwwUUPDBiJIGLWDKJAQeQiUaVEQAEEk7XFGIFet5UPREpJ6f8DFKhngw0EBAOJOBxg8QJOBRggzXhSk" +
    "yBD2EZ1yvYD64oJlfGmC5WuW5Mr/+BiAtxcKhieSiiIoeMKiuIRHWw4KFQVGAKkmEEOKyJBGxtjfTNSuCUGM2M4zf8DG5RhRLK2o" +
    "+EABg8QLFExhMIU2wWwKQeQqkiQmgcUEwKeMAKhIMUspQJf8DGBnpYa3mYgSOGmCJQaQEjgyVhiTBxTkTkxhiIcamoKqJUylmALD" +
    "Smp/8DHZxkAK8LBIRqGICsAQRIBwoxEgMxMpEYc4kIbqI6CEa5MrY1uXGty42xr/4GJhfFxCMJJyPEGzAUIFHEQwCXjWAjTADiFL" +
    "MA0NMms9J3IstXKA1LHk+f/gYjPsoBoBEJABxcUJBAh5oioSMciMGIMWkfKuC3FGp4R2QiQmskkpV4l2h/wMdDPXgEsVRMHIEwwM" +
    "QCEigYRFAMcxMxU40IBnwTGNuJeRtZyKsACLYuU4f8DGJFjwnA0oiIGRhMYPCAh5AJUg0hEYQ1ZVQlALQKRkjpmSGIuDWFM2NbB/" +
    "8DHhro5imjIssRKBQYIMNHCgFIELKFELKFU6hzzCfGcTY0oU9UjJDE/4AtfaZ0f8DEplngVBTweCzgcQIGkhpAWQFLgLaAEWgewe" +
    "kXAq8QzJxJrEtQxmNJW9EcX/AxcL5SHQhTEwoMMCEjAB5ISQGGMAQk49Itw21npTW+0qpmJLO9g01rpKIP+Bj0m0QmYjIWGjhI4A" +
    "SOGkAo6SowAiSgwFQNTSIicU0k7WAlX/AGF3xsQoAaHm/4GNDXYzFFHw0oHBCRwsoRKDSyaxZQTJh4wBk6YpXytjGcginhUx6piI" +
    "fOtn/AxiHaICwlKJAAwQOMGkgos4SgEOYSQAkguMpUNdIIhQKIx0m66Smcuctv+BjQ518nSRkeSDghZYuaImB5xqwopBLQZAQ5JJ" +
    "1qKMxG/8AZdSG6SBkjqFNMBG/8DHqRuBYXCgWMBGyA8EEHliKQ4yKRpwY5SJBWPIJcCjISS2KVrjiKdGtxT/gYuC/firigmxA0MD" +
    "HFxxEYTOXQTKROZUVMTOTGIuD3DGYTXAtAO07MCp/wMdn2nB8JSBgULBlh5oaIIFQwybA45ipyYQhMa5f+AMau3LAAA9JXTIiYc9" +
    "pDNh/wMfGunjKuYhZAOAHHFxxUULAYeIEGW8W0IiklDHoE+NMFxvlSw4AABOf/AxuUaICwNOLBgUGKIhAQscFDIJAEMWUGGqZAWZ" +
    "piIoAiVLjWw7EsGqHff/gYsN9fFWslBggkgRNFTQ8cJUJIOPEAIi18/ANGFGDMRGGpYhLceC2FGYimf/AyOgbUGwdKGBREAodJEQ" +
    "gpCaDKVMRKPGFOXIIijOJ9M1K1HNFOs0swkSTnD/gY4F9jC4EjlIUKOLjBYMkHDIKhEIikIlFhAEdySMWh5BFKhbHfUmttjbX/gZ" +
    "JOt8Bng0BAxEoJFAwogGIENQH/Dur1x4a4ggYh5xKTWFPKR872HUMSUEmV/wMfJeziryVgAgkoVMDRwskLKAegGKMGMMKusaCLUK" +
    "qFBlXAMjLgE+2it7v+Bi8g0wdjLAWBwkkTJAwYIGMXWZEGLSJIJSJIKNT0RMiVEJFACOgHRie7/8DEyDtYe3lYGOKiAoomGEayCI" +
    "OwYsoc41AlQ8w1Y0gYyEOxLkqO45FPQ9mpv+BjNK14A8GQoNJBwA44uOIgiCyDkRAgGnGtSTxVvUKRlDqITMohVHIQRRoH/wMXD+" +
    "khjmfjIsQTJGRxEQNDBGnANOHK4gABAAAAcQAAAPCAG7/2v/7//sDwgB7/8SAAf/+/8ICvdXendnegghsCg4IgQBggEB4YDgAIJD" +
    "AcFHFx3/AdB/wT75scQmWx0FwUBYgFhgEHgQEDgYQINIBQoYMLJFmEoGoCgFGEKUxEsKCb/+ByDpE6ZW0jBQILDhIwGFHEwQYWwa" +
    "YKKQFxv+AR9A+2eMKcqYmUWQGYDsi/4DiP+CgXO0Qmo8C4IigeMCIkDgYIDDyQMWeCiiI42MPKTGEPSJQHCRjONB2NQNn/A5h0qS" +
    "KccXRsHAAQcELJCxAgIPIBjlIkBlHlIgOiZMYQzoI1wqFL/4Dhv+CfnQETio8CYSDQoAHiwSIBocJLCRBAqMIgEmTFTlRCE1BQk/" +
    "nUUDAyjxAIP/gco6RXGtpIw0WDRASSDhxxMUXEBjVCzAxzkQJKiAImC5VsKJ862B/wHPf8E/ucIRCygJw8BAgDDA8CBA8SGlAocQ" +
    "FEAxAMxEQIcAiLCbB5iXHNFGmDXf8DkXWK43s4yDhgeHFQwckbHERQ8IGMMWgesWwekioTK+APYD3JlT8X/ASl/wVE7cmcuEAJA0" +
    "QCxIFAA4gNiBUQEFlBpYaUHljUDUi1j1DWk1DVj4DGQy5f+By7oFKUZQrlYUFhAOKJiAgkUHDESxYxiJR4wBTESCNcUZCJYuCY3/" +
    "8Bv3/BP7piRw8jCMCAgCBwMKEQYCETQ8YDDjBoIEJSLOHAGcycmgyY8xUGfGUqP+BxzqU2RZM0k4MEzYaLBBQODIFwwAYakSYOKU" +
    "iUeIOdEYDNlfS1QwJ/wHQf8E/ukn8QUANgkBAoKDAgOBhAGGABjCooWCCkDHnEpDhgKJIACKms6CHOz/gcs71ajddMQAGGCY4qIC" +
    "ihYIAAApiJi5ipiZyIISKshEqZAAR8q/+A4D/goB2FKILNQmCAuHCIQDhAIGiAMCi95Fgk4cERKBQ4o0IY1Q1AcMpMgB2JHKX/gc" +
    "c7pWCmWNY+MgQKEnA4oWEABAEVD0hwBhCEnEmHM2CY0qTK1xxL/4DgP+CePYlEiREEQHB4oDgAMOFwYADFDQwIWKBghJgEVCzgww" +
    "inQCTKtyWA2A/+ByDvVmN5A0k4EFhgKDGEQQYSIFDyAwhCzAIpflhKSwyWhUExhJccjXf8ByX/BO7sKRS3/wm+6/2DsPYIjAQJCA" +
    "LBADAYQFgA4LABQeGCooOCDnBpL/gY9QjoyRiIEBSHIJgQYKMJiiYwaMVKHFSLIEREES46AfLE48ck8kq2FK55A/4GOEFPN5IqHB" +
    "iiYgELHAyWgxCDShxBRREKNAm2yRvcMjWHKqS8U0lk7x/wMdkRkok2RQGEBCRgcMcmcmgqYOAYU5Y1EaCGmG6IgjxtQKTUCXWXV/" +
    "+BiItHanlMuiqwoIaOFjhIwKAlQhkUw8gsg0wHrTSdiJBPjWoVCkghc9M4f8DF5oST9DDkAQcELGACyB6g4AiTCUAwHICH0yUxVt" +
    "UUBqiQA0XbtXMaa/8DGw+Kp4hSJHBQYBIqMVOPKRMRKLKXSTIepaniENNZ5SqiIYMXtslv+AKzlh/wMklgmHPDRYqQAHkBYoWoaQ" +
    "AkotI9AcopUJRI5phkIuDXDPkNI1OLJP/gZSQydOrDhRhUQCFjAYR6Qo5RpAZjaEzJDAJLlyrjSw5prWsOR8qXLli/4GSyoCEyrQ" +
    "YGDiBZAWOHMLSPKFEJMHISxKhRGI+B2HJHEiJjf+AL3aOZTyGP/wMgCoSXbrxBMMRLDxQcgBJxISBoaiahc8RmNIRrkuXAp2EFux" +
    "oTWjTt/wMflgMDqUBQiaHkB5wmQJOFCJMAekWcGmkALCpAEGuczY2wKLGQzyU0/4GLiUIHSyMQJBBBooKMWYOIgeMGMAi1DKyQhg" +
    "agYpJ/wBVc86hSKiIZahjR/wMbhwuhh1hISGEDRQsIKQeciEU68SkGMB5xFPKVjTAmcyVFMp9ElU1j/gZCS0VPLMQgskDElgYYEG" +
    "KEMSYOIacGdCHqOI4iprPCyEymoA7NLbPKX/AyKeFgSxdJCZQSKDigoAYgBBR0gCDkU9EUJGRf8AXsoclYI5HzrclDokEfGX/gY+" +
    "GRcpLHQ44EDBERgMZNI1I1As4kwtBLlqKAmuKm1s4FU1C0cu";

  // Tone24Mono48000: 1 ch, 24-bit, 48000 Hz, 4200 samples, 2 frames
  private const string Tone24Mono48000Cookie =
    "AAAQAAAYKAoOAQAAAAAwBAARlAAAALuA";
  private const string Tone24Mono48000Frames =
    "AAAEAAAPCAGz/3n/6f/s5RlBc6HSACxaiLLjET1vncn8KFKCsN8RP2eXx+4iUn6s1wc1aZPD7hhKfKbXAS9dx4E8/LpyL/GvZSbi" +
    "nlYT0ZFJBMSEPfuzdTDuqGYn351VEs6ISAnBfz70tHIx6adlINkNOWmVwe4aSnyq1QU3ZZO97BpIeKTTATNbjb3oFEJsntD5LVmF" +
    "seYMPHCYzPkpUbl3MvSubCXlo1kQ4LKEVCX7zZ1xPw7itIhYKAHRoXdFGOa6il4x/9eleUka6sKOZDYISIzTE1ed2iBiqu0tcbv+" +
    "PoDJB1GT1BhanuEnZ63sLHK0+T2FwgpQktkbX5/gJmjkuIpcKgHTp3VJHOa+kFw0Bdele0ke8MCQaDoN2a+BTyD0xpRoPA3hsYVT" +
    "KPjImmw+DlSY3SFjqeYwcrL7O4PGCkiSzxdVh7XgDDxslsb3I1GFq9oINmqUxPMjTXut2go4nlgTz41JCMSAO/25bzLqpmQl2ZdV" +
    "EMyIRAfBfzz6snAt7adhHtqcWBHNi0UEwn4596/gDjhqmMT1I1F9sdwKOmaSwu8hUXmp2AAuYIy87xVFd6PP/i5ehrrjFUVtn8v6" +
    "JoxKDcV/QPa2dC/vq2Um4ppWFdGNSwTGfj37tXEy7ppuRBHltYlXLQDQonBCHeu/kWMtebX6QITHCVGT1hhYouElabHsMHq3A0GH" +
    "xghMlNUbXaHiKGqw7zF1ugJEhssNVZIP5bWHWyj2zKJyRhfrt49hKwLSpnRGGem/k2MzAtyofFAd78eZZz0M2q6AUiPzx5drO4PG" +
    "Bk6M0xNbn+AkZq7tNXO3+D6ExQtLj9QSWpzjJ2mp6jZ2uQFDg8f4JlSCrOENby7opGYf3ZtXEsyMSAfDfzz0snIr56VdINyUWBHL" +
    "jUcCwn47+bFrLOimXh/XmVcOzoa25RNDbZ/N9iRYgK7jDT9pncf2JlB8rtcFNWWPw+oaRnqk0wE1YY296hpIcKTU+2Uk3ppaE9GN" +
    "RwTEfD/9tXUq5qhkH92ZVw7MiEYJv4E69rByKeenYSDelFQVz4dE/r56ouElZ7HyNni6/z+JxgxSlNkZXaPiJmys8zF9u/5GiM0N" +
    "T5HaHl6g6S1vr/I4ers5Ct60hFQp+8mfcUEU5LCKWin5z6FzQxDquIxeMAXXp31HGuy+lGA2B92rgVEg9sKSZKjvM3W3/j6ExQ1L" +
    "kdYUYKDhJ22t8jh0vwFDg8YIUJDVF2Gh6ChssvU1fbgARIrHRRrqwIpiMAXTp3dJGtqYUhHNi0MEung19a9rLuigXh/Zl1UKyoZH" +
    "/7l7NPSsaiXjoVmPu+QYSHCe0PktV4e35g48bJrI+ydXh6/gDjZmmsb1IVF/qdwGOGSUwvEbR3ul1jv7s3Uq6KhiI9+bVRDMiEYB" +
    "v382+LJsJ+ujYyLcmlYPzY1JAL56O/WxbSzkoGAf15NPfa3aBjhokMbxI095p9QINmaMvvENVZfWHFym5S9rs/g4fMMBRYvOEliU" +
    "2SFlpepoNAfZq39TIPTClGo8DeGxgVMo+MiebDwP4bWHWTEAzqJwRhvnu41jLwbSpnZIG+u/jdYWXqLjKWmv7jh4vQNBicYQTpLX" +
    "GV2n5ihsrPE1d7/+RoTPD1WT1hpiouctba/ydEIT57eNXSr+1KByShftwZFjNQLapHhMHe/DlWU5Btqqaivho1kY2JBSDceJPPq8" +
    "cjJgkMDrGUl5o9QEKlqIuOkXRW+dzf4qWIi24Q8/b5nH+CJQfrDhBzdplcX0HE56qxLOhkoBvX849rRuLeWhXxrWllIPyYVDAr52" +
    "NfOvcSroomAd1ZdTEMaEQfu5ezb0rmgiVoSu3w09Z5nD9iRQfqjdCzVnk8HwHkh2qNcBL12Ru+gaSnCi0QExXX3CBkyO0xOPZzEC" +
    "1Kp4Sh3txZFpPQzarH5QI/XDm2c9Dt62iFQn/9GhcT8U4rSMWC//0adxRxjquv9FhcgMTpTbHV+h4iZsrvc7e8H+SIrNE1WX2Bxk" +
    "pOkrb7X4Nn6/B0uNyhRSmuEhmW9BEuC0iFwp/9Ofc0cY5riKWi4F1al1RxrwvpBkNgfXqXtPHPLGmGY6B9uzg1Mi9sUNUZG97BxG" +
    "fKjVBzNdj7/sGEZ2oM7/LVmFs+QSPmyazPklV4Oz4BA6aJbE9yVTf+mlXRralFARy4lDAr52M/etayTkolob15NNCs6IQf+9fTDw" +
    "rmoj5aNdGtaOUAfHhTz7J1eFseASPmqcxvcnUX+z3Ao8apbC8SVPf63WCDZiksLvH0d3o9IGMl6OuOkZR3PZm1MSyoZCBb95Ovay" +
    "ZjYF2619TxzyxpJkOAvhr4FVJvrGmGhAD+G3hVUq/NCgcEIZ4ipwrvU3eboCRorRDVOb3BpipukxbbH2NnrBAUON0BBSmNkdZaXm" +
    "LnK29zmDwgZIxppmPAvdtYVVKPbInnBAEeO3iVkpAMygckgb67+LXS8E0qp4SB/vw49lOQTWqH5MH/A0dr7/SYXKEFCU3R1fpegq" +
    "brL1OX+8BDBaiLblFUNzodH+LlaGsuETQW2dzfQmVrx6OfOxbSTgpFob15VRCMaEP/m7eS7srmgl5Z9dHNKUTAfFgzz6uHY18a1r" +
    "KOKaWhXSAixgirzjEUNvo8/8KFiGtOcPP2+XyfogToCs3ws1aZXF9B5QeqrVCTdljb3oGEasbC3jpWEY2phMD8mHRPy8dDPvq20i" +
    "5J5eHdWXUQzEhkP1yZVtOw7csIJQJ/fLnWtDEVeX3CJipu0vc7f2NoLFCUmNzhRUmOMhZ6voLnS49T99vgpIkNURWZ3eHmSm7zFx" +
    "88GTZTsK2KyATiP1yZ1tPxDgsIBUJ/fLn3FHFui2hlouA9GndUUW7LiSYC4H1ad7Sx1hpegqbrD1OX3EAkaI0RNZm94iYqTpL2+1" +
    "+Dx6wQdHjcoUWJbfI2Wr6ipunsz7J49PCMiEQ/+5dy7wpmQp351bFtKQTgvDfzz4tHgx76lrIuKeVBfPi00GxIA/+bV3MOym2QE1" +
    "YZO96hhKcqDTATFdibvmFkZ0nMr9K1eFs94OPGqWxvUjT32t2go2ZJDC7x+JRv66ejPzq2co4JpeG9WVTQzGgkH7vXcw7q5qJ9+d" +
    "XxTUkEoHyYM+/rZ0L+utZSTgmMj5JU2T1BZUmN8jZavuMnS6+T1/yApKkNUVWZncJmSm7y93ufo6hscHUZHSFF6bGPC6kmI2Cdmn" +
    "e1Eg9MKUZjQJ3at9VSbwyJZoQBPlt4lXKPrMnm5EE+m3i2EzAtKkeEqIyxVVmeAeZqbrK2+5+D6CxwVLkdIYWprdH2Wn6jB0svk/" +
    "fcQKTIzPGVeZ3iZorSj8zKBqQhXjuYVbLQDMnnIx6aVjHuCWUhPRkU8GwoA9+7dxMO6mYCPZmVUQzo5EA799qdoGMmSOwPEbS32l" +
    "0gA0XI667RtJeaPP/ChaiLThFT9rn836JFSGruUPOWubw/BaFdGTTwzCfkH7uXcu7qZqH9+fWxjUkEYLxX88+rhwMeupaSTcmlgZ" +
    "z4tLAsKAP/u3b6HR+CpcgrTjEUFtnc36KFSGsuEPPWubtgBAhMUPTY/SGFyi4ylpse40drr/QYnKRhXnuYljLQTWpnZMGe/BkWM3" +
    "BtSofEoh88Gbaz0M2rCCUCf3zZlxPRDksoZaKf/Pn22z9jyCxQdHk9AUXJzjI2mn7jB0tv1Dh8gESpDRGVmf4iZoqO0zd7f+PoTJ" +
    "D1GV0lQh98eZaT0O4rSGWCv7zaFvQQ7guopcKgHNo3NJGuq4jFw0BcN/PPS0bi3nqV8c1phSgLDfDTdrmcfyIkp4qtkLNWWTwewe" +
    "THao1QMvW4m95BZGcKDTASlZibPiDkJsoMcy7qZqIeGdWRLUjEgHw4M69rRyK+2pZxzYmloR0YtHBsSAPfmzcSropGYh35tXDsqI" +
    "Rnai0P0xX4e36BJEcJzK/ylVh7XiEjxsmMT1J1GBrdgKOmSSwvEdTXup1gQobq7xb0UU5rSMWDH/zaN1RxbmupBcMgHXpXlJGuy+" +
    "kGg2B9mvf1Ek8sSWbDgN26+HUyb2zJjjJWet8DByuP89g8IKTJTXFVmb4iJsru01dboARILLC1GX0hxanuMla630NHS6/X1PHu7E" +
    "lGI2C9+xg1Ek8siWbjgN37WDWST8zKB0RBfpuYdbLv7UonRKHe3BjV83BNKk6S9xs/Y+ZpzG8yNTg63cBjxolsTzH015pdYGNGCS" +
    "uO8ZRXej1f4wXoy24xlDb54Fw31A9rhuK+unYSLellIR0YtHAMKAPfWxbzDspGYd3ZlZENCGRAHDezj2sG4t659jHUt7qdICNFyQ" +
    "vucVQ3Gj1fouWIi05xVFcZ/H+iJWgrDjDT1tmcX0JkyAsNsHNWmV+7VzNOisYiPfnVsS0pBIBbWNWy8C0qJ0RBvvwY1lMwjYqHxO" +
    "IfHDk2U5CtyqglQj98gMTJLVG1mh5iZoqu8xebn+QITFD0+V2hxeoOUlb6/sNnq7AUWFzA5SktsdXZ/oJqZ8Sh3tw49hMwTWqH5O" +
    "IfXBlWc5CtysglAj+8ubcUMS4LaEWi39z6VvQRLqvIxcLf/SFlac3SVrrewycrz5PYHGBk6U1xtdo+IoZKrbBTdjk8XuHkx4qtUB" +
    "M1+NvewaSHjYllYT0YlFAMR8O/mxbSjmpF4d25VVEsqGSAW/eTbwsHIp66ddHtiYUg3NiUj+unw38h5QfqzbCzFnj7/qFkp4pNEH" +
    "LVuLvewYQG6e0PsvWYe14hJCcJzK+SVVhbHeDDhs0pBMA8WBPPaycDHnp2ce3pRWDc2PQwbCfjv3s3Ms5KZgH9mXSRzqwo5mNgnb" +
    "q3lPIPE3e7wARIbJDVOX1BZepOMra632NnjBBUeFzAxQmNcZYaPkLGyu8zd/wgJIis0VUc2jcUMW6rqOYi4H1aV5RxrswpRiNAvd" +
    "r39PJvbImGg4DeOxgVck+syccjwT5bmLVy75QYPGDlCQ1R1dn+AkbKrvOXm5/kCIyRFTldQWXp7nK2+x9jJ8vv9DicgOVJjZHU2x" +
    "bSjooF4Z25lVDsyKRf+/fTT0rGgp6aFbHtSSUA/Li0UAwHgz77FvKOKgYBfVkU0OxPknUYGx3gY4aJjE9R1LgafYBjBkjsDrG0l1" +
    "pc/8KliItOUVRXOfz/wsVIKw4Q87o2Mg2JpQE9GJSQa6ejvzs3Em4qJiG92TTxLKiEIFwXk08LRqK+WhXR7UkE4Ny4VC/LzrF0dz" +
    "odPwOH7DBUeLyBJWmN0dY6nmKGyw8zt/wAJEiMsRVZfcIGao5y9zt/Y6gPrQnnBAF+O3i18rAM6idkYZ57uPYTUA1qZ8TiPxxZFl" +
    "NQbeqoBSJffHm207DNy0gFgmbKzxM3e9/EaKyw9Tk9QeXqLlK2ux9jh4vwFFhcoOVJLXHV2n6ipurvM5f8IGSosG2Kh+Th31xZNr" +
    "OwbarIJUIfXFgT7+unQ38bFvJOCcWh3Zj08OxoA//bd5NPKqZiPfn8v6KlaEst8NP22bxfYiUICs2wk7Zf9xxz7T7T7X2hPBGAcA" +
    "AAAAAAAAAAAAAAABgUCIEAAAAAAAAAADBQiEAAAAAAAAAxREQAAAB/wOO/4T07Ig8gIwmCgBgwAAAAAAIJDA4AAAISMDgAAAIkwc" +
    "AAAJLDgACSw4f8HHO+UpnbyELEgkQEkBJASQEjg4AAAAAAABqiQAAAAA55wAB/wOO/4T466gAqUxmFAGDL+gJAONiIUJhAAAAAAA" +
    "AAAItAlAlAlAlItBMEwTBME/8HDOoP5/NHMzDwgAAAAAADEAAAAAMgAAAAA0AAAA0AAADj/gcd/wnh2Q8g4nCgHggAAAAAAAAACF" +
    "kBJASQEkCUBwyAAAAAAAlwTBMEwTD/g5J3aMJMiYSEEAgcAAAAGIAAAB+GIlpBEoEoEoEoEnDgAAAAADn/wOe/4Tw7IWQ3QBAGgY" +
    "ABBIYDgAAAAISMDgAAACJMHAAARLDgAAJLDgAFL/g4h4CPJb+YgAAAAAAGKIiAAAAAAAMpEgAAAAABqiQAAAA/+Bwn/CfHdzeBJy" +
    "GQYDgAIJDAcAAAABCRgcAAAIkwcHC/4Cdx4kaGQAAAAAABLgmH/ByTwWFHcgYSEGAAAYgAAAAAAGQAAAADIAAAABoAAAHAAA/4HI" +
    "f8J199OQEKQrCgQCRAJEgsQCRASQEkBJAODEAAAAAAACLgmCYJgmBxoAP+DjnhcSMZQzk4AAABiAAAAAAAZAAAAAMgAAAAGgAAB/" +
    "wC8JsnAA/4HHf8J4+A2cQTkNgYDgAAAAAAgkMDgAAAhIwOAAAAiTBwAAJLDgAAJLDgP+DjnlMuLW8hCRALJCSAkgJICSAkcOAAAA" +
    "AAADVEgAAAAHPOAP+Bx3/Cdvgl5C05DYGA4AAAAAQSGBwAAAAQkYHAAAARJg4AAElhwAAElhwP+DvWdu4rBDMPCAAAAAAMQAAAAA" +
    "BkAAAAANAAAAOAAADgf8Djv+E3/D8dghSFYVBYgEiASIBIgEkA4MQAAAAAAAABFoEoEoEwTA40AAAAf8HHPN50RyhnKQIHAAAAAx" +
    "AAAAAABkAAAAA0AAAADQAABwB/wOO/4Tb8ayCD0MNgQBBYgEiFGBB4cDhIwOAAACEjA4AAAESYOAACSw4AACTX/g5F7Pi7eym4SI" +
    "BIgEkBJAWQEkBJASgSgScOAAAAAAAaokAAAAf8DkP+E3fHc8kBGEwTAAIJDAcAAAAAQkYHAAABCTBwAAAIkwcAAJLDgAAKVf+DkX" +
    "s+Lt7KbhIgEiASQEkBZASQEkKj4WPFlQ4AAAAAGQAAAAaAAAAP+ByH/CavjWmTgfhcAAAAAAAAAQWICSAkgJICSAcGQAAAAAAAlw" +
    "TBMEwTA40f8HHPVbkuyhnJwAADCAAAAAAYgAAAAADIAAAAA0AAAA4AAA/4HIf8Jq+Q59Ix+FwAAAAAAAABBYgJICSAkgJIBwZAAA" +
    "AD8MphQYAAAASWHAA/4OOe34+6t5CEiASHA4AAAAAAAAAAykSAAAAAANUSAAAAA55x/wOO/4Tb8dzyQEcTBMAAAAAEEhgOAAAABC" +
    "RgcAAARJg4AAAElhwABJYcAAf8HHPYcRZ28hCRAJEAsgJICSAkgJICThwAAAAAAA1RIAAD8v/ASerClDg/4HHf8JqeNaXOR+GAAA" +
    "AQWIBIgEiASICSAcGIAAAAAAAAi0CUCUCYJgcaAAAD/g456ndF2VMpOAAAAAAMQAAAAAAGQAAAADIAAAADQAAAcAD/gcd/wmp5Dn" +
    "skH4YAAACCxAJEAkQCSAkgJJCyAkgJQJQJQHDIAAAAAAJcEwTD/g5J63XsHtEGJwgAAAAAAAAAYoiIAAAAAABlIkAAAAAGqJAAAP" +
    "+Bx3/CbflGTwBAEANBAGDAAAAABBIwOAAAACEjBwAAESYOAAAJLDgAAKVX/4OOe34Gst5GDgAAAAAAAAAGKIkAAAAAADKiQAAAAA" +
    "1RIAAH/A47/hNvyTLoUSRSFgQBgwAAv5wsBBOEiAkgJICSAkkLICUCUCUCUBwyAAAAAAL/g5R7TbFeRMJCCAQOAAAAABiAAAAAAG" +
    "QAAAANAAAAA0AAA4/4HHf8Jo+X5rGSAFwAAAAAAAAAAAQsgJICSAkgJIDhkAAAAAAAlwTBMEwTA//ByD2GkGMoZycDCAAAAAAAGI" +
    "AAAAAP7QktwgAAAAAaokAAAAAc/+Bz3/CanleDyWgCAGgYAAAgkMBwAAAEJGBwAAAAiTBwAAAIlhwABJYcAAF/wcm+CWxBZxkAAA" +
    "AAAAYoiIAAAAAAAykSAAAAABqiQAAAAc/+Bz3/CaHl2KxCZhMAAAAACCQwHAAAAhIwOAAAAESYOAAN//gJnvAphKBKBKA4ZAAD/g" +
    "457fSDWTM5OAAAAAMQAAAAADEAAAAABkAAAANAAAADgAD/gcd/wmb6Dk8EKQrCgQCRAHAwgAAAAAAAAAhZASgSgSgSgSkWgSgTBM" +
    "EwONAB/wcc99qxrJmcnAAAAGIAAAAAABiAAAAAAyAAAANAAAADj/gF4fhk/4G/f8JuemZJEZMFADBgAAAAAAQSGBwAAAAQkYHAAA" +
    "RJg4AAASWHAAElhwH/Bxz45dDtvIQkOBwAAAAAAAAAMpEgAAAAAA1RIAAAAA55wAP+Bx3/CaPpGVwubBcBgAAAAAAAIJDA4AAAIS" +
    "MDgAAAIkwcAAAJLDgACSw4D/g458cwOVQlfYVMnAAAAAAMQAAAAAGQAAAAAGQAAAANAAADgf8Djv+EwvU9LjI/DABBYgEiASIBIg" +
    "EkA4MQAAAAAAAARaBKBKBKCYHGgAAAAP+DjnxqzGcoZykCBwAAAAAGIAAAAAGQAAAAANAAAANAAAAcD/gcd/wmF61nsEKQrCoLEA" +
    "kQCRAJEKMDlRoMAAAACEjA4AACJMHAAACSw4AACT/wcQ+dYqlv5eAAAAAAAAGKIiAAAAAAAAZSJAAAAABqiQAAAD/gch/wmP7Fn8" +
    "LmwWAYABBIYDgAAAACEjA4AAAAIkwcAABEmDgAAJLDgAClX/g5F9MydTZTcJEAkQCSAkgLICSAkgJQJ0f+Al8uLOjQwABkAAAAAG" +
    "gAAA/4HIf8JcezbdLh+GAAAAAAAABBIgEiAkgJICSAcGIAAAAAAAETBMEwTBMDjQH/Bxz6NkKbKGcnAAAMIAAAAAAAxAAAAADIAA" +
    "AAAaAAAADgAAf8DkP+EuPbdgjI/DAAAAAAAABBIgEkBJASQEkBJISQJQJQJQJQ/JNsx1AACJMHAA/4OOfYs9WW8hCRAJDgcAAAAA" +
    "AAAAGUiQAAAAAA1RIAAAAA55wP+Bx3/CX/tmswolCkLAMAAAAAEEhgOAAABCRgcAAAARJg4AACSw4AACSw4AP+Djn2LPVlvIQkQC" +
    "Q4HAAAAAAAAADKRIAAAAAAaokAAAAA/+AKn/ASnQT/4HYf8JQ+sa3JisLwwAQJEAkQCRAJEAkQEkhJASQEkBJAlAcMgAAAAAAJME" +
    "wTBP/Bwz6Jh6bNHUzDQYAAAAxAAAAAAAMgAAAAGQAAAAGgAAADgD/gcd/wlp7tsEZH4YAAACCRAJEAkQCRASQDgxAAAAAAAAESgS" +
    "gSgmCYHGgAAA/4OOfVMDM5Q02Q3JDIIAAAAAYoiIAAAAAAAykSAAAAAAGqJAAAP+ByH/CYHvOeSCchoDAUDBgAAAAAAQkYHAAABC" +
    "RgcAAACJMHAAAElhwABJq//Bxz7hj5a4j4SIBIgEkBJASQFkBJASgSgSgScOAAAAAABoAAAA/4HHf8Jd++6dFpyGgMBQMGAAAAAA" +
    "u5g1BpeJICSAkkJICSAlAlAlAcMgAAAAABJ/4OHfUrkJ06HJpOBhAAAAAAADEAAAAAGQAAAAAaAAAAaAAAB/8Dhv+EsPiaxwEnCc" +
    "IAQAAAAAAABBIgJICSAkgJIBwZAAAAAAACTBMEwTBMDj/4OLfdsXKZc2loOBhAAAAAADEAAAAAAGQD8NWrTIAAMgAAAAAAGgP+Bx" +
    "3/CWnxBWYrOQyBgHAAAIJDAcAAAAAhIwOAAAAESYOAAAiTDgAAJLDgAF/wcm/I9RQWcZAAAAAADEAAAAAAAAAGQAAAAAAAaAAAAA" +
    "A4H/A47/hLH4otUKmwWAYAAAAQSGA4AAAACEjA4AAARJg4AAAET9H/ASHhiWmQACJQJQJ/4OGfbsPM5o5mYaDAAAGIAAAAAABiAA" +
    "AAAZAAAAAGgAAAOAAP+Bx3/CVPxdZ4IUhWFAQCRAHAwgAAAAAAAAAQkgJIEoEoEoDhkAAAAAAJMEwT/wcM++Y6ZzRzMw0GAAAMQA" +
    "AAAAADEAAAAAyAAAAAaAAAA4AH/ALz/gdJ/wl39CYQACAGgQAwYAAAAAIJDAcAAAAEJGBwAAAESYOAABJYcAABJYcP+Djn5XrKW3" +
    "kIWIBIgEiAkgJICRwcAAAAAAAAAyAAAAAABwAAP+Bx3/CVvxtcoAgCAHAMAAAAAACCQwHAAAABCRgcAAABEmDgAASWHAAASWHH/B" +
    "xz8r2dZbyFnzZoAjkNBgAGIAAAAAABiAAAAAZAAAAANAAAAHH/A47/hKb4uwUHE4UA8CAAAAAAAAAACEkBJASQEkBJAcMgAAAAAA" +
    "EmCYJgmCYf8HJPyPUUmRMJCCAQOAAAAAxAAAAAAAyAAAAAaAAAABoAAAcD/gcd/wlF8iYKDicKAeBAAAAAAAAAABCdeCUMhgcEJG" +
    "BwAAAESYOAACSw4AACT/wcQ/O95Z38vAAAAAAAABiAAAAAAOAAAUAAAA0AAADwgB0/9R/9wAAZnB7h5MdqjZAzFji8HqFkh4ps7/" +
    "MVuPu+QQejn3s2km4qBiHdWXTwzGhkIBuXUy8qpoJeGjYxjalk4Py4VFArp2OfOvZyjmoF4b05HD6hpMfKjVBy9hkbnoGkZwos79" +
    "LVmHu+ISPmap/xAb7w7w7y7wD8IggAAAAAAAADChEIAAAAAAAAD/4HCf8KY7REQiMA6CgAAAgkMBwAAAABCRgcAAAEJMHAAAAiTB" +
    "wABJYcAACl/wcQxkhaY8nkISQEkBJAWSEkBJAlAlAk4fhf8BN+A=";

  // Noise16Stereo44100: 2 ch, 16-bit, 44100 Hz, 800 samples, 1 frames
  private const string Noise16Stereo44100Cookie =
    "AAAQAAAQKAoOAgAAAABABAAViIAAAKxE";
  private const string Noise16Stereo44100Frames =
    "IAASAAAGQSHIEFD3RpCqJhq8nyAUVtGlTnLZPIO5CSAKg0ZcTESbsm+92xEEKikEliqVKqtWqtxCcCAnYhSVXaLEfC5VXRnNQ5PN" +
    "vZzHfhsJsVXjbBau5m5Eey5AXs4/uDgDLjbdBOptZVqZiVtWbtM6DgwqQKmSozNZfHxA46DMvc4vJakwMl7rOWANQmOuk5p/lHbv" +
    "bFnyZ7hqO84GBKUYYzAUC3Jx08WqAzBDXDI2jOeNrqLSW7r4H3JpgXSWUPjBXc24qBfLfHaNyI0C+PCyDi71QcJfpeSUPMA4dygo" +
    "9nkAz8y7Q5GC7TlwtCGlP5dK4TgaItWaDK6Vvz5UM8yPoZVwypm6tTHkaIe5hoTjrHYvLejr19JBjHCqSGbYJCrVt8aeNukRyb6m" +
    "Ov4MkupR78lOyhEmyzPP65NsCuVfFz8vtJ6X4MZuZKB8UpVrpcKii+JGnClJg6NNTS6iyvOKiOzhg8FiQDlFNAfsCVSzLgJ69UyV" +
    "7lu0vQN2eZ+joKTrCL9yv8wuG1dgXGlZOvSoBsBaNxEzVDJXoHqacS9wbSK+hfetMYz7Gk/Gz364lSs1s7DCKFXVVTnjg06Z27PQ" +
    "dnsyBadBmZybUVqLeAkKlpLKWBsBW8NVqrKIt5q4+qa3x5P411ngtWXg8XJUExG5tquEy8P3SFuDGElfA4MtsDVeNZRofjLak50t" +
    "xR5kpkK3ICLNo37ccBxOSjZmm2yT0SFwBJdcqJDCU3go9Tcc0Dke9YDc+T+MXa7cl2UMLdrwE2nenEmmPB/uB6jzYwbjZMB9rrEH" +
    "c4yuvxZFnoklA4RkBRzFP9QwVI/TvEZ0OuftSQmHb/zENQku1WjHa1BmAWz1IlviIqaecJ5CHpfiLgsiqp5l0M0w4tDAkoyy/VFj" +
    "rbC/uYHNvboA9YGyoGbygeND+fAnaBVDoka8sA216zDNeiA9DlN/884oIkYReFqaQnP7dEK8YLfLnUz3zFNReZda5k0nf90UlFM/" +
    "IwwYbCgnpnddFzd3T5XCByzq9XzSBiIVWA1irnsyVlWYZIgfhJoWoRs9jKSreH8hJwkFWls6aBXXsFm1BLPfSP+MU0mT0L0dKvK7" +
    "H+wQYTLCcS61t3qOvUmlApsaR15quKJKsbskXfEOIAYDwCS/QeQZakMWNL1IMyJG7qtGEGwucI3/7xuEjVJbAFRcobSwe5b9py/+" +
    "5FolE1gpLzP2cNJgfcirXInJitV7AXqaLVZ7MGdjPpy9/7YBta2pudv4GozHhO6/h+JOcZbcX1HTb9/NeusK8ceqhh8WwpqnUPWN" +
    "sV2aRzpghUO3tKfUJR+WrQFQkOEPTDc7SY6YG/azuq0ze1LD9sS/FNiHADKnTtj1BkmXmCpd64UHaEu/ySMJDyOk3v86Jwd1rQB7" +
    "VIxqqMi+CCCQpdBwGoNA2KZojAJMN6dcGn3DPR+0X4adsz7gR7WBQawGSNq4kfkpeEWiNgXKks3CVqCr1BgqgvYdY8GUGujtXPot" +
    "piusuBBp+92d4+jGGiiPif5lqC2y2fs38tzLwACXXa64Pfz0RSxHgJGVPeMYBAsTUJ7cf0Q/od6KWUbORtYqx1vHTGJpAhWZ2Ncc" +
    "1oKa45ohX9V9TKuNSQBBuiJsJYs0QqcRCQS2d/alZ4nT+bRRQ1aIWcvJKmIvNNz3FgkOzoOLxGMqiJalMocTJFQLpLf5QwfcWJpQ" +
    "8A10eHZHmqpqALkOC2FOfAC1f6dBHCdDoXOazXJbkjotKm9qX5yIlADGtX5yf5fEEqPy/dQ6q/PDLYLV4U5kjTKXPg90RyD0V7XX" +
    "EbGriVqP8LD5ewDXnvhpfSOM+qxxSCdmzSy8nHtbc9jNfks5rUpY7YF8CNa4Qjd8wIdr8J/ceM4Nor8WWCZ13MNCEJqySmBEh8c3" +
    "vjvRatvCiPebToL1ykeXVZpO+PBwCAj5k++3TsAE8beJpvKeVUTwOwJG+csT+HTOEqM454i8hUPqZ+E2z/o3/xcGIjgRZsgdZNMl" +
    "7cukTsFYI3YggAkVeU6rQPVAc4PGNO0IZ6NWv8vlxxMdedveDyolZi4aGbhrXNR4KVl7XhOUcm0cAUUuuY98+eATLobeMIfqaoQk" +
    "IzWSglM+uzEFMNE6QhWKcBanW90zie48Up/3rwvzUG+jN1rfwWt1slCwb2+m1gkZH5YiUEgn063yBvSN87F6OTYaBJfYp/sry3PV" +
    "wtqsqIuX2q3M5J7kKMEYipL8VWfXg9LJ5eGzLcihl1ttSqwFGHgFpM3gkrhmwRr9w6hY4prSlsqHPBpRxKaIODOLtBocZPOhUjR1" +
    "SSSem36gm/se6RzrD8eCMxVkXvyQXVRkVf2jzRzxCXj1J6lyIjunRrgl+5SKdGsVjOzq8W69jS+AICP+fLWrnoc53MHoKb4JtL6z" +
    "qhLn0qA2sB2kxq4+Q9b/fTwPPY+tMjPa7raHB99+LjCCbP/JhfkGa6VyEp2e+A7zhgauUzKQ8O2pX/rCJOjxCb48JH0wIlTwxzNT" +
    "Awnr12sigrW6hqJXCeeVtWIEMI91ShVIReJo/3Ykt2L0DSHfdpuIg7TF01LF7flogHD5mV1WcOGmmOl4aiONux3+br1OxwDUWdb0" +
    "2WU8EVTWHk2gTFus70kgKDriajJdT/sWCtLExfHeaT/m1KpMQFOSo0t3HBT7/gsVxJ3wCdSE58Bri/qPoLHyU4GkSgN7/xHUPbih" +
    "2hTAtQSiAPNdNOVse4ioEgM7WrI+tQ9/cNYSryUllj0S1K89t2Ia82AVuAS+FwEGsZiRr3CY9u2+s/BBQ7k9h8FbEpFQoKK6LJly" +
    "62vTGRILITC4wknmhPv2H2g+un5jz01gYl799mDHaa4gx30Uu2+8QGN46RF+HBBLkZnw2vsL3y8t1x8dPxm5MXSE4MjMIuDsDTuo" +
    "TlsC90/mMClzvzHGPjMXt8P59UPke7jTqGFRjIveHboi3nUlJ2RTORVp3UR7feeAQH0WSNyQ5yrY0A4+mMaUXbgaH6L8zbQENPic" +
    "IfXecT2T+SGSUtvy0R/FWwi6eYjU4Gib/x6lcG7vut+q4vNPs2DtnHWuRjGq7SoZesF2Pm4XZWRNBTwNZwVB+r2rHXu39xz+yXeE" +
    "VLBbNxSwnQZsfn345S1MsXDn6WM1stOGXh5PkKLvYRSB2SZlBVJtNiZl3FJrx77g9eqoQ7J5DiHFygSeydRJPDoqvX6FiHjd9YSr" +
    "6i3FS3NSegZIhn01qeOpX+Kc6C4EdawrkBsJK5a9S/2DSV4J1q2mYiiouEehWKVMPjImQ0WFdinsMw8ZzdMtmx/HUzdIk4PK2vup" +
    "cFEtu2PehBLUmSuhFjUgXwKs7qnqDpTlOsn1M/WiRVgCzsnt4DV1s19mj08ATSNDyC4zQf7ti+enHTDYOAc5WXTyBj+sAcyaiNZC" +
    "q5JiXZJ/DiiFlZdkrTDYCamf2Gy/aWEjyFVDQuYb4DzoJurcplTVxAcNM8wVuFGr1NM0ZCupgsOcD0ZxNQlD2kW+opdkq85dZ3Iz" +
    "T4ZFqqigJn2HxiWL9OO6oNazb33mAQCRZjsFFbZKdE9k7QTK/k+YVidA9nQuvt0s4w6O3pBmPAUTGQ6D+FpyhGq/T2ISMs22e9Jg" +
    "A05jpA/mhtd9bstskUl+osG3UGsbq/2m7KyfEdakPMy/mQjpsBvb1TODiC4Tmm27P+joCaVOK66pAvdWNKzEyfu98ifGplZLpTQF" +
    "zrOGcnox8ueg9nNWN5yznjqehz0R0s5nhU2RyhZAUKc42nGjMpedFikxEBc4nLwGAyQG+ocoT7nQhc6ORjoS4wlDp5hWORtRR7wT" +
    "i9JBjqaaIPDgM6YhQIL9OYsMjxkzfuhfeIWhBW9FR0dWTOb6+5Yw7VdFwJJft4iUI8QDax6BEbPwgipdWRPJZaoUuD+MMkWKTRaw" +
    "Wn42QYpO8yB5LZ9KqzE98Iz4TIAJO8Op/e1TiEU5LHaXD2yKsIJAQRrwFWgw+cfdZkc1+b1FFW5ArYV4fR8t4s2JcRN9xIF9kQa/" +
    "iRiNYZslPrf97ZD1ioFw+9V2guiA628DylefsrmBEigUIrdvomfkY6bwa3FFlt+SqGl2XLFGSYfwhiD3o/28gbXzy38yOkZzVgir" +
    "v63GpNBEa5Onkp2pDAQ/5JexeruhYxWnRFAOecqzW64/nL1540B79xESFSZJ1JwOCB3cxwZZ/6yhzbyb9K3zWnu3ix2Yg4NLDeE6" +
    "ZJxznknp7Gml3B8Ky5U9iM8hecwdHF6uVnMwVb41egcKCjw0w/ftzhzygIFyTwAbQiyXwu4Bygz1wA==";

  // Silence16Mono96000: 1 ch, 16-bit, 96000 Hz, 5000 samples, 2 frames
  private const string Silence16Mono96000Cookie =
    "AAAQAAAQKAoOAQAAAAAgBAAXcAAAAXcA";
  private const string Silence16Mono96000Frames =
    "AAAAAAAPCAEAAAAAAAAA/4f/8AAAEAAABxAAAA8IAQAAAAAAAAD/gcPw";

  // Tone16Surround48000: 6 ch, 16-bit, 48000 Hz, 600 samples, 1 frames
  private const string Tone16Surround48000Cookie =
    "AAAQAAAQKAoOBgAAAADABABGUAAAALuA";
  private const string Tone16Surround48000Frames =
    "AAAQAAAEsAAADwgBs/99/+f/6/9xxzLTJzJWUgtASBAAoCQOANA0AgFgUAoEAmCQDgGBAEBwKDAiDAiBAQNFAULGAILDgYksEEiB" +
    "g8MCNMETKTGIRQB/wLc/4Pn+cL4QsRQIAYUGgQIGjhYwAWIBERg0Agxpg5gByC4NjKVTQQcCGOaLEShqNEmX/gsl+jli2wjYeEEC" +
    "wg4aKLig6KAY5hogAAKxo5VwOMRP1/8BK8ZEkkoBIxjRuGNTxIql/4Fnf8HufTq6kMRcCgA4PBgIJEDB4IMJEBhAkgIY1IkY5MgR" +
    "bmxvgCTGENNYzAc8QsAqRl/wWu/NwSBOqOKgoMMDECQQUcPKPEDMNCAMWYU8DJMYh3JIYzWHyxcyol8I2Mnv/wLY/4Pa+kT9oZDA" +
    "EAgMHCAQNJDSAMXnTCQwWGEQghaR6R6A5g4xjTHjEdjXDA8aJjuRRACUn/wWc/aziQJZqBgQkUHCihIIEFHKLDWPSJKDDCMlRwQ1" +
    "gJMZEUpysTlbSmUr2uo/4Fof8HvfUKzEWY+HAYJCgUCAw44EDBhgYIIScKWsKIEGKQ0wARaiiGmUYQuNrZUuv/AFr/gI3nJos/8F" +
    "pOJP7O6qIqHhAUaQIjgRUYLAITILGGPOHMNUSo5lJIB4GKdhk3eDVjYnmq/8Cyv+D4fqFLbGA6EgAGFB4MABiiYYEDEmAQccw8IY" +
    "04UI85MGztUBSiEUgABAAAASwAAAPCAG3/3P/6//sDwgB7/8SAAn/+f844p+Z9J977wjgZAAAgCQFADAOBACAWCQCgGAwBASDAEF" +
    "QEBgWFASDgkOAwUIAwoNAggkQOIjCoj/gOO/4J9dTQaBEQRA4DgITCAAAAAAAQcOIBCSA0UAaoOKUmUSA5EQj4FBM5EsH/wORdsq" +
    "i65jIeMCIkJHCSQUOQKggg4hqhqA46CpAAGgi5YqXxplbK3/gOE/4KD9YRWIkURA0JBaXlh0LioeBAYUTGExxcgXCBh5QcdBUgAp" +
    "iZyZS6pHTGEP/gcm6dGjmRNZOChgiICCQwoONIDSBKRJBipiJAxZBUSAE+Ncb41sA//Acp/wT26qiMWsQ1D4OBQMOFw4RAgISQDg" +
    "hYoOAEGpHrIqErIrIrEqGmHASWHLD/gcy79XC2SKpmHgQIEkBIwaWIkAYfYglxYpExkw0QAAzESCTPJKc6okf8ByH/BPXsKSxSbh" +
    "wBgYGCQoFBQgCBwoomOKjCIwiECNWNQLKASUKATVCmU8QgT/wOMeD3ZffysHEBsMHiAo4qIECxAosgloABjTDVi0mxyUplWoZIpV" +
    "z/8Bzn/BPHsKTRKYg8CgMADhQiEAwWFBwo4aCBiAYo8YMznf8AkcGDZgxTDwILlHjClImN/wOVeH24pkjCQgwADBgw0gFDihYouK" +
    "HNQLKFAESUKJbFsJRCRUyDJZ/wHOf8E5u2J7DakLAiGBMWBwkaBAkIDi4wiIABkDI4uUqkuQIWwm4mgKItzYDOyL/gca8LvxzMm0" +
    "rBwAAEIlBYoGB/zjgm8m4m8t3BKAoCYDAMgUA2AoEQGAYBwFAQAgLBYFgoCBsEAICgMFCoMEB4kHiAATMDSg8kJJDSQ0sakSgf/w" +
    "MjpRUIOBkOAgYwiIEggYgSEEOUKGEUmWwes8qZyoK9iZYpYo2uO4p4wEv/Ax0jnJOeRkhY4eYFigoZNxNI1pNIcMIp0BkmhRHMQi" +
    "Z4o1zrNChX/AFj8T64Yv+Bj86RBOOqRgJJBAYcUVIGyTqSZiohBJRKBahca3HEcBkAQ3YI735Tw0f8DJBWRlrKEOhBRkEHFCRgC0" +
    "D0C0BRQiIimENdJ6RgYSXFPsOKBp+OtO6/+BklGQAvFQCwMMDFEwwYisOOQAMo8IQmD6YrYo4pUxpQgja/+AMqyQElIp6Dgb/gYy" +
    "P0M1ijYcKKLjhoMoJQFJaHSdQRCEJQOeFTJHUCMciXNcManme/KeJ/8DD4sNGKdYIBEQgAQAsg1ZFAlIsgdAlCXAtSYJUmC2LUSp" +
    "hxPtHnSMyf8DHxqZxjM+DHFxhEICBjkADObQXMRKTEM+M4lxnO7/gCl0V0QinlI1QJUdR4/+BikoOIWRPEAoMMFDCjoQtIkoMdBU" +
    "YM5MgilQRrCkOmsZEY4irmvijbGuf/gZAFS1LHExYwGHLBQgIMAYw6wpyJB5zyAR87UAkzFiRUZrjzNyIAEAAABLAAAA8IAdX/U/" +
    "/UAAYPCAH1/w4AA//9/zjhlSlTqlVGCUAQBQDgUAAAAAAQEQUA0DgFAICwcBwcCQkCwMBAQLgAQFCRQCAwkoHKAhYYgRDAyEyhwy" +
    "gjwgDNgdiVLlOYQiRf8BJ3/A2HmQESkAEGBYEGGgwQYeFJAjzADhFEgGLIeYbXHMMakjUdQWu7A1iebItbVVIddCbPJ5hP+BKDil" +
    "MVCJwoAUURHIiCEkBg1/+ASGm6UaIekWMKYWYMALGUxDwewTRElWlbZOk3OZvobYJA8f8BK3/A1XkRwLLhACAwaOBDwZIOCJFxyJ" +
    "Spx4gBCzhQxCGUQGOg6lxrgth4TMmxkb5Ji4esmilc0D9f+BKDZiVMohCiRwIWIETcRMKJGNGNGGcikmaiKVUU7RGi/4ApJ8QhFE" +
    "UolWTjREqIxmytY2eJxRsP+AlL/gbBzobIRIKBQoFAGBCJAAQDFkBhgIHAYmsKGpLEqGM0UqooISBCLO2Uoe9K22oU7RZpRhExcv" +
    "+BKzmFsU7TgBBpQSGDCEoHoEmChDjKWOVJlPQ0EDWpLk1ld4txbR0jELiZf8AMn/AI3A2SQOGYqBN/4CSv+BqXSjggNB4IBxAJEA" +
    "wAAoQMHDFJjDEkBhkDhsXGlAHIpYKSQpRqUssbW0te3GIFEur7CXDZ1LP/gSY3on/nHBJvJ1Tim0CIAwEAPAGBgBoBAQBEAwUAkD" +
    "AFAcMAUChACgAEBYQCQwJEA8SBxARLDRwcUDABiCIgCGUhC0CSgwDLS1gysiBzwEiYx4Vf+BEEgJWFBAMAlAARpwoxJhJENQN8Dm" +
    "a4pEFBA9ye9kradCOufDrohGbYZ0KSVxOk89K5zy5df+BEQ6pkkpEQJCAC/VTihGjGgDECNOGeVtMzCLQNFUoJpocQ4OG+hiuvFE" +
    "AJ5yvRGVdEjNm3yIZ8/+BDUsA+XDhJgWkEEy4SIGGoWUMZDNjbGlB3FABW2kV5P1Rb8u9iSV1fIjfQAHPB5HLg2fi3l45/8CHwUa" +
    "ZOlRQcEgqsGeYOIYaMtH/AFswUEu8WLAoJnAqnkAQ081yjJrZGoiSA2fZYtFj2ok3anMS2P/gQ3FIQZoaMFkBHlEiBhAEKx6gKDB" +
    "PBi0NUtVkS0Jnxabk+SYmt8QViXaVW3uT3owpejSytP/gQ0ShogyMFkAoYwpyIEmWCDSjRuFEOd7hRC/4AqdKICewqZ0kEUwyUK7" +
    "nM1qkq2mVl62EzxMWmsSv/wITpCUW8QByQMYIcJA8YlYdIR8Y1xomPOMQEACAAAAlgAAAeEAPn/hgAE//3/uOKW+WyttboGQIgMA" +
    "mAgBoBACAaCQEgUAATBYCwUBoGCAVBQLBAVDA8EBAkMCxYNBCRUcTDCDZQMNQJMJQLKDGNKHcdQz1p/4KMrjwEGuKAgQMOKIRELK" +
    "AOEQKGmAFMJKgW5bCnjB8mtU1E1xpjK2SvcGzSRCL/gok/gncMlABAw5YGA5EgVNAtIkwUYRyAr/gFXjnjjpDHA6BrjMkxjJQUlN" +
    "gtdb2PS1ZT/4KErI2DiyBYaSGigiIgphogYgw5zWFElRTTUrQSZCyDJGb6HWyHXMo7dVY66xiu99/+CfhtjFVjFOCFiBIUYGIOII" +
    "ESYGGCFmGqaCyxpIg4izwiFqkanC0au+VAP+AUmoU5gEv/gouaXFoDwQSFjhY4OIQWIAAhqRIJWuW5aAGUx4xokjkIRX5vVYWkNr" +
    "FBWjU642Wv/BRCCgn8IdAElAg0gewmseoWYKSoISoFuijBrilZEDEjjSp8rbHaLDLNA1INMbUh/+CjahcOn1BQIAHIABDmEkBIjB" +
    "E/dVXORGAElh2FKYRQGY/BrQm8UQ2R2haNXBRq/P/goQbLnYQqFEgDgAxyCkR0AgkRgGDokJBCRIqlBMYLEiIYqmYhZX4A==";

  // ── Decoding foreign frames ─────────────────────────────────────────────────

  [Test, Category("HappyPath")]
  public void ForeignStream_Tone16Stereo_DecodesBitExact() {
    var expected = Tone(5000, 2, 2);
    AssertDecodesTo(Tone16Stereo44100Frames, Tone16Stereo44100Cookie, expected);
  }

  [Test, Category("HappyPath")]
  public void ForeignStream_Tone24Mono_DecodesBitExact() {
    // 24-bit streams carry the low byte of every sample outside the residual coding,
    // between the prediction headers and the residual blocks.
    var expected = Tone(4200, 1, 3);
    AssertDecodesTo(Tone24Mono48000Frames, Tone24Mono48000Cookie, expected);
  }

  [Test, Category("EdgeCase")]
  public void ForeignStream_Noise16Stereo_DecodesBitExact() {
    // Incompressible input makes the encoder fall back to uncompressed (escape) frames.
    var expected = Noise(800, 2, 2);
    AssertDecodesTo(Noise16Stereo44100Frames, Noise16Stereo44100Cookie, expected);
  }

  [Test, Category("EdgeCase")]
  public void ForeignStream_Silence16Mono_DecodesBitExact() {
    var expected = Silence(5000, 1, 2);
    AssertDecodesTo(Silence16Mono96000Frames, Silence16Mono96000Cookie, expected);
  }

  [Test, Category("EdgeCase")]
  public void ForeignStream_Tone16Surround_DecodesBitExact() {
    // Six channels arrive as a chain of elements in one frame, in ALAC's own speaker
    // order, and have to be placed back into the container's order.
    var expected = Tone(600, 6, 2);
    AssertDecodesTo(Tone16Surround48000Frames, Tone16Surround48000Cookie, expected);
  }

  // ── The fixtures really do cover the paths the names claim ──────────────────

  [Test, Category("EdgeCase")]
  public void ForeignStream_NoiseFixture_UsesUncompressedFrames() {
    Assert.That(FirstFrameFlags(Noise16Stereo44100Frames).Escape, Is.True);
  }

  [Test, Category("EdgeCase")]
  public void ForeignStream_Tone24Fixture_UsesShiftedBytes() {
    Assert.That(FirstFrameFlags(Tone24Mono48000Frames).BytesShifted, Is.EqualTo(1));
  }

  [Test, Category("HappyPath")]
  public void ForeignStream_ToneFixture_UsesCompressedFrames() {
    var flags = FirstFrameFlags(Tone16Stereo44100Frames);
    Assert.That(flags.Escape, Is.False);
    Assert.That(flags.BytesShifted, Is.EqualTo(0));
  }

  // ── The cookie as foreign containers actually carry it ──────────────────────

  [Test, Category("EdgeCase")]
  public void Cookie_Parse_SkipsFrmaAndAlacAtoms() {
    // A CAF 'kuki' chunk wraps the config in a 'frma' atom and an 'alac' atom, the
    // shape the reference decoder's Init() peels before reading the config.
    var config = Convert.FromBase64String(Tone16Stereo44100Cookie);
    var wrapped = new byte[12 + 12 + config.Length];
    WriteBE32(wrapped, 0, 12);
    "frma"u8.CopyTo(wrapped.AsSpan(4));
    "alac"u8.CopyTo(wrapped.AsSpan(8));
    WriteBE32(wrapped, 12, (uint)(12 + config.Length));
    "alac"u8.CopyTo(wrapped.AsSpan(16));
    config.CopyTo(wrapped.AsSpan(24));

    var parsed = AlacCookie.Parse(wrapped);
    Assert.That(parsed, Is.EqualTo(AlacCookie.Parse(config)));
    Assert.That(parsed.FrameLength, Is.EqualTo(4096u));
    Assert.That(parsed.BitDepth, Is.EqualTo(16));
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  private static void AssertDecodesTo(string framesBase64, string cookieBase64, byte[] expected) {
    var cookie = AlacCookie.Parse(Convert.FromBase64String(cookieBase64));
    var decoded = AlacCodec.Decode(Convert.FromBase64String(framesBase64), cookie);

    Assert.That(decoded.Length, Is.EqualTo(expected.Length), "decoded PCM length");
    for (var i = 0; i < expected.Length; ++i)
      if (decoded[i] != expected[i])
        Assert.Fail($"PCM differs at byte {i}: decoded 0x{decoded[i]:X2}, expected 0x{expected[i]:X2}.");
  }

  private static (bool Escape, int BytesShifted) FirstFrameFlags(string framesBase64) {
    var frame = Convert.FromBase64String(framesBase64);
    // 3-bit element tag, 4-bit instance tag, 12 reserved bits, then the 4-bit flags.
    var header = (frame[2] >> 1) & 0xF;
    return ((header & 1) != 0, (header >> 1) & 3);
  }

  private static void WriteBE32(byte[] buffer, int offset, uint value) {
    buffer[offset] = (byte)(value >> 24);
    buffer[offset + 1] = (byte)(value >> 16);
    buffer[offset + 2] = (byte)(value >> 8);
    buffer[offset + 3] = (byte)value;
  }

  // ── Source signals: integer-only, so the PCM is identical on every platform ──

  private static byte[] Tone(int samples, int channels, int bytesPerSample) {
    var pcm = new byte[samples * channels * bytesPerSample];
    var full = (1 << (bytesPerSample * 8 - 1)) - 1;
    var noise = 0x12345678u;
    var index = 0;
    for (var s = 0; s < samples; ++s)
      for (var ch = 0; ch < channels; ++ch) {
        noise = noise * 1664525u + 1013904223u;
        var value =
          Triangle(s, 97 + ch * 13, full / 3) +
          Triangle(s, 311 + ch * 7, full / 9) +
          (int)(noise >> 30) - 2;
        WriteSample(pcm, index, value, bytesPerSample);
        index += bytesPerSample;
      }
    return pcm;
  }

  private static byte[] Noise(int samples, int channels, int bytesPerSample) {
    var pcm = new byte[samples * channels * bytesPerSample];
    var state = 0x0BADC0DEu;
    for (var i = 0; i < pcm.Length; ++i) {
      state = state * 1664525u + 1013904223u;
      pcm[i] = (byte)(state >> 24);
    }
    return pcm;
  }

  private static byte[] Silence(int samples, int channels, int bytesPerSample)
    => new byte[samples * channels * bytesPerSample];

  private static int Triangle(int index, int period, int amplitude) {
    var phase = index % period;
    var half = period / 2;
    var ramp = phase < half ? phase : period - phase;
    return (int)((long)(ramp * 2 - half) * amplitude / half);
  }

  private static void WriteSample(byte[] pcm, int offset, int value, int bytesPerSample) {
    for (var b = 0; b < bytesPerSample; ++b)
      pcm[offset + b] = (byte)(value >> (b * 8));
  }
}
