#pragma warning disable CS1591
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using Compression.Registry;

namespace Compression.Tests.Documentation;

/// <summary>
/// Renders the support matrix of the filesystem package README from what the
/// descriptors themselves say.
/// </summary>
/// <remarks>
/// <para>The columns that can be read off the code — the id, the N/A / R / WORM / R/W
/// state and the maintenance verbs — are always regenerated, so the README
/// cannot claim a capability a descriptor does not declare. The columns that
/// cannot — the link behind a name, how a format is proven against outside
/// tools, the caveats, the specification — are hand-written in the README and
/// carried over row by row, keyed by id. A row whose format is gone is dropped;
/// a format without a row appears under the last heading with those cells
/// empty, for someone to fill in.</para>
///
/// <para>Rows are grouped by the <c>###</c> heading they sit under and sorted by
/// name within it, so moving a row to another family is a matter of moving the
/// line.</para>
/// </remarks>
public static class FilesystemSupportMatrix {

  public const string ReadmePath = "Hawkynt.FileFormats.FileSystems/README.md";

  public const string Begin = "<!-- SUPPORT:BEGIN generated by Compression.Tests/Documentation/FilesystemSupportMatrix.cs — Id, State and maintenance capability columns come from the descriptors; the other cells are kept as written -->";
  public const string End = "<!-- SUPPORT:END -->";

  private static readonly string[] Columns = [
    "Format",
    "Id",
    "State",
    "Compact",
    "Compress",
    "Canonicalize",
    "Repack",
    "Sort directory entries",
    "Defragment extents",
    "Change allocation geometry",
    "Wipe",
    "Shrink",
    "Purge",
    "Proof",
    "Notes",
    "Reference",
  ];
  private const string Alignment = "| --- | --- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | --- | --- | --- |";
  private const string DefaultFamily = "Other";

  /// <summary>What a hand-written row carries that the code cannot supply.</summary>
  private sealed record Row(string Family, string? Link, string Proof, string Notes, string Reference);

  /// <summary>The assembly the meta-package compiles its formats into.</summary>
  private const string PackageAssembly = "Hawkynt.FileFormats.FileSystems";

  private const string FormatsBegin = "<!-- SUPPORT-MATRIX-FORMATS:BEGIN";
  private const string FormatsEnd = "<!-- SUPPORT-MATRIX-FORMATS:END";

  /// <summary>
  /// Every descriptor the package delivers: everything compiled into the package
  /// assembly, plus the formats named by namespace in the meta-project's
  /// support-matrix region.
  /// </summary>
  /// <remarks>
  /// <para>Those named formats compile into <c>Hawkynt.Compression.Core</c>, because more
  /// than one package delivers them and a second copy would give their types two
  /// identities; the package dependency on Core carries them to consumers. The key is
  /// the descriptor's namespace rather than its assembly precisely so that moving a
  /// format between assemblies cannot silently empty this list — an assembly name is a
  /// packaging decision, a namespace is the format's own identity.</para>
  ///
  /// <para>Only that region is read, not the whole project file: Core also carries stream
  /// codecs (ZIP, LZMA, zstd, …) that these readers decompress with, and those are not
  /// filesystem formats and have no row here.</para>
  /// </remarks>
  public static IReadOnlyList<IFormatDescriptor> Descriptors(string repositoryRoot) {
    Compression.Lib.FormatRegistration.EnsureInitialized();
    var project = File.ReadAllText(Path.Combine(repositoryRoot, "Hawkynt.FileFormats.FileSystems", "Hawkynt.FileFormats.FileSystems.csproj"));
    var namespaces = DeclaredNamespaces(project, $"{PackageAssembly}.csproj");
    return FormatRegistry.All
      .Where(d => d.GetType().Assembly.GetName().Name == PackageAssembly
               || namespaces.Contains(d.GetType().Namespace ?? ""))
      .OrderBy(d => d.Id, StringComparer.Ordinal)
      .ToList();
  }

  /// <summary>
  /// The <c>SupportMatrixNamespace</c> items of a meta-project's support-matrix region.
  /// </summary>
  /// <remarks>
  /// The region is required rather than optional: an empty result would quietly shrink
  /// the matrix instead of failing, which is how a documented format stops being checked
  /// without anyone noticing.
  /// </remarks>
  internal static HashSet<string> DeclaredNamespaces(string project, string projectName) {
    var begin = project.IndexOf(FormatsBegin, StringComparison.Ordinal);
    var end = project.IndexOf(FormatsEnd, StringComparison.Ordinal);
    if (begin < 0 || end < begin)
      throw new InvalidDataException($"{projectName} carries no '{FormatsBegin}' / '{FormatsEnd}' region.");
    var namespaces = Regex.Matches(project[begin..end], @"<SupportMatrixNamespace Include=""([^""]+)""")
      .Select(m => m.Groups[1].Value)
      .ToHashSet(StringComparer.Ordinal);
    if (namespaces.Count == 0)
      throw new InvalidDataException($"{projectName} declares no <SupportMatrixNamespace> in its support-matrix region.");
    return namespaces;
  }

  /// <summary>The README split around the generated region.</summary>
  public static (string Before, string Section, string After) Split(string readme) {
    ArgumentNullException.ThrowIfNull(readme);
    var begin = readme.IndexOf(Begin, StringComparison.Ordinal);
    var end = readme.IndexOf(End, StringComparison.Ordinal);
    if (begin < 0 || end < begin)
      throw new InvalidDataException($"{ReadmePath} carries no '{Begin[..20]}…' / '{End}' region.");
    begin += Begin.Length;
    return (readme[..begin], readme[begin..end], readme[end..]);
  }

  /// <summary>The generated region, rendered afresh from the descriptors with the hand-written cells of <paramref name="section"/> carried over.</summary>
  public static string Render(string section, IReadOnlyList<IFormatDescriptor> descriptors) {
    ArgumentNullException.ThrowIfNull(section);
    ArgumentNullException.ThrowIfNull(descriptors);
    var (families, rows) = Parse(section);

    var grouped = descriptors
      .GroupBy(d => rows.TryGetValue(d.Id, out var row) ? row.Family : families.LastOrDefault() ?? DefaultFamily)
      .OrderBy(g => families.IndexOf(g.Key) is var i && i >= 0 ? i : int.MaxValue)
      .ThenBy(g => g.Key, StringComparer.Ordinal);

    var page = new StringBuilder();
    page.AppendLine();
    foreach (var family in grouped) {
      page.AppendLine();
      page.Append("### ").AppendLine(family.Key);
      page.AppendLine();
      page.Append("| ").Append(string.Join(" | ", Columns)).AppendLine(" |");
      page.AppendLine(Alignment);
      foreach (var descriptor in family.OrderBy(d => d.DisplayName, StringComparer.OrdinalIgnoreCase).ThenBy(d => d.Id, StringComparer.Ordinal)) {
        rows.TryGetValue(descriptor.Id, out var row);
        page.AppendLine(RenderRow(descriptor, row));
      }
    }
    page.AppendLine();
    return page.ToString().ReplaceLineEndings("\n");
  }

  private static string RenderRow(IFormatDescriptor descriptor, Row? row) {
    var ops = FormatRegistry.GetArchiveOps(descriptor.Id);
    var name = Flatten(descriptor.DisplayName);
    var format = row?.Link is { Length: > 0 } link ? $"[{name}]({link})" : name;
    var cells = new[] {
      format,
      "`" + descriptor.Id + "`",
      State(descriptor),
      Mark(Compacts(descriptor, ops)),
      Mark(OptimizationCapabilities.CanCompress(descriptor)),
      Mark(OptimizationCapabilities.CanCanonicalize(descriptor)),
      Mark(OptimizationCapabilities.CanRepack(descriptor)),
      Mark(OptimizationCapabilities.CanSortDirectoryEntries(descriptor)),
      Mark(Defrags(descriptor)),
      Mark(RelaysOut(descriptor)),
      Mark(Wipes(ops)),
      Mark(Shrinks(ops)),
      Mark(Purges(ops)),
      Cell(row?.Proof),
      Cell(row?.Notes),
      Cell(row?.Reference),
    };
    return "| " + string.Join(" | ", cells) + " |";
  }

  /// <summary>Whether the format exposes genuine physical extent defragmentation.</summary>
  public static bool Defrags(IFormatDescriptor? descriptor)
    => OptimizationCapabilities.CanDefragmentExtents(descriptor);

  /// <summary>Whether what no file holds can be zeroed.</summary>
  public static bool Wipes(IArchiveFormatOperations? ops) => ops is IWipeEmpty;

  /// <summary>Whether the volume can be reduced to what it needs.</summary>
  public static bool Shrinks(IArchiveFormatOperations? ops) => ops is IArchiveShrinkable;

  /// <summary>Whether every live entry can be erased, leaving a valid empty container.</summary>
  public static bool Purges(IArchiveFormatOperations? ops) => ops is IArchivePurgeable;

  /// <summary>Whether the format exposes at least one real allocation-geometry control.</summary>
  public static bool RelaysOut(IFormatDescriptor? descriptor)
    => OptimizationCapabilities.CanChangeAllocationGeometry(descriptor);

  /// <summary>
  /// The size-oriented composite: real extent defragmentation, compression and
  /// shrink. Allocation geometry stays an explicit separate action.
  /// </summary>
  public static bool Compacts(IFormatDescriptor? descriptor, IArchiveFormatOperations? ops)
    => Defrags(descriptor) || OptimizationCapabilities.CanCompress(descriptor) || Shrinks(ops);

  /// <summary>The repository's write scale: R/W over WORM over R over N/A, read off <see cref="FormatCapabilities"/>.</summary>
  public static string State(IFormatDescriptor descriptor)
    => descriptor.Capabilities.HasFlag(FormatCapabilities.CanModify) ? "R/W"
     : descriptor.Capabilities.HasFlag(FormatCapabilities.CanCreate) ? "WORM"
     : (descriptor.Capabilities & (FormatCapabilities.CanList | FormatCapabilities.CanExtract)) != 0 ? "R"
     : "N/A";

  private static string Mark(bool offered) => offered ? "✅" : "—";
  private static string Cell(string? text) => string.IsNullOrWhiteSpace(text) ? "—" : text.Trim();

  /// <summary>The headings in order, and each row's hand-written cells by id.</summary>
  private static (List<string> Families, Dictionary<string, Row> Rows) Parse(string section) {
    var families = new List<string>();
    var rows = new Dictionary<string, Row>(StringComparer.Ordinal);
    var family = DefaultFamily;
    foreach (var raw in section.ReplaceLineEndings("\n").Split('\n')) {
      var line = raw.Trim();
      if (line.StartsWith("### ", StringComparison.Ordinal)) {
        family = line[4..].Trim();
        if (!families.Contains(family)) families.Add(family);
        continue;
      }
      if (!line.StartsWith('|')) continue;
      var cells = SplitRow(line);
      // The hand-written cells are the last three, wherever the derived columns
      // end. Reading them from the tail rather than from fixed indices is what
      // lets a verb column be added without the Proof, Notes and Reference text
      // of a hundred rows falling out of the table on the next render.
      if (cells.Count < 5) continue;
      var id = cells[1].Trim('`').Trim();
      if (id.Length == 0 || id == Columns[1] || id.All(c => c == '-' || c == ':')) continue;
      var link = LinkOf(cells[0]);
      rows[id] = new Row(family, link, Blank(cells[^3]), Blank(cells[^2]), Blank(cells[^1]));
    }
    return (families, rows);
  }

  /// <summary>
  /// The address behind a linked name. A Wikipedia address may itself end in a
  /// parenthesis, so the link runs to the cell's last closing one rather than
  /// its first.
  /// </summary>
  private static string? LinkOf(string cell) {
    var open = cell.IndexOf("](", StringComparison.Ordinal);
    var close = cell.LastIndexOf(')');
    return open >= 0 && close > open + 2 ? cell[(open + 2)..close].Trim() : null;
  }

  /// <summary>An empty marker reads back as no text, so a cell nobody filled stays a cell nobody filled.</summary>
  private static string Blank(string cell) => cell.Trim() == "—" ? "" : cell.Trim();

  /// <summary>The cells of a table row; a <c>\|</c> inside a cell is text, not a border.</summary>
  private static List<string> SplitRow(string line) {
    var cells = new List<string>();
    var cell = new StringBuilder();
    var body = line.Trim();
    if (body.StartsWith('|')) body = body[1..];
    if (body.EndsWith('|') && !body.EndsWith("\\|", StringComparison.Ordinal)) body = body[..^1];
    for (var i = 0; i < body.Length; ++i) {
      if (body[i] == '\\' && i + 1 < body.Length && body[i + 1] == '|') { cell.Append("\\|"); ++i; continue; }
      if (body[i] == '|') { cells.Add(cell.ToString().Trim()); cell.Clear(); continue; }
      cell.Append(body[i]);
    }
    cells.Add(cell.ToString().Trim());
    return cells;
  }

  internal static string Flatten(string text)
    => string.Join(" ", text.Split('\n', '\r').Select(l => l.Trim()).Where(l => l.Length > 0))
             .Replace("|", "\\|", StringComparison.Ordinal);
}
