#pragma warning disable CS1591
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using Compression.Registry;

namespace Compression.Tests.Documentation;

/// <summary>
/// Renders the support matrix of the filesystem package README from what the
/// descriptors themselves say.
/// </summary>
/// <remarks>
/// <para>The columns that can be read off the code — the id, the R / WORM / R/W
/// state and the maintenance verbs — are always regenerated, so the README
/// cannot claim a capability a descriptor does not declare. The columns that
/// cannot — the link behind a name, how a format is proven against outside
/// tools, the caveats, the specification — are hand-written in the README and
/// carried over row by row, keyed by id. A row whose format is gone is dropped;
/// a format without a row appears under the last heading with those cells
/// empty, for someone to fill in.</para>
///
/// <para>Rows are grouped by the <c>###</c> heading they sit under and sorted by
/// name within it, so moving a row to another family is a matter of moving the
/// line.</para>
/// </remarks>
public static class FilesystemSupportMatrix {

  public const string ReadmePath = "Hawkynt.FileFormats.FileSystems/README.md";

  public const string Begin = "<!-- SUPPORT:BEGIN generated by Compression.Tests/Documentation/FilesystemSupportMatrix.cs — Id, State, Defrag, Wipe, Shrink and Layout come from the descriptors; the other cells are kept as written -->";
  public const string End = "<!-- SUPPORT:END -->";

  private static readonly string[] Columns = ["Format", "Id", "State", "Defrag", "Wipe", "Shrink", "Layout", "Proof", "Notes", "Reference"];
  private const string Alignment = "| --- | --- | :---: | :---: | :---: | :---: | :---: | --- | --- | --- |";
  private const string DefaultFamily = "Other";

  /// <summary>What a hand-written row carries that the code cannot supply.</summary>
  private sealed record Row(string Family, string? Link, string Proof, string Notes, string Reference);

  /// <summary>
  /// Every descriptor the package bundles: all of <c>FileSystem.*</c>, plus the
  /// <c>FileFormat.*</c> disk-image projects the meta-project references by name.
  /// </summary>
  public static IReadOnlyList<IFormatDescriptor> Descriptors(string repositoryRoot) {
    Compression.Lib.FormatRegistration.EnsureInitialized();
    var project = File.ReadAllText(Path.Combine(repositoryRoot, "Hawkynt.FileFormats.FileSystems", "Hawkynt.FileFormats.FileSystems.csproj"));
    var containers = Regex.Matches(project, @"FileFormats\\(FileFormat\.[A-Za-z0-9]+)\\")
      .Select(m => m.Groups[1].Value)
      .ToHashSet(StringComparer.Ordinal);
    return FormatRegistry.All
      .Where(d => {
        var assembly = d.GetType().Assembly.GetName().Name ?? "";
        return assembly.StartsWith("FileSystem.", StringComparison.Ordinal) || containers.Contains(assembly);
      })
      .OrderBy(d => d.Id, StringComparer.Ordinal)
      .ToList();
  }

  /// <summary>The README split around the generated region.</summary>
  public static (string Before, string Section, string After) Split(string readme) {
    ArgumentNullException.ThrowIfNull(readme);
    var begin = readme.IndexOf(Begin, StringComparison.Ordinal);
    var end = readme.IndexOf(End, StringComparison.Ordinal);
    if (begin < 0 || end < begin)
      throw new InvalidDataException($"{ReadmePath} carries no '{Begin[..20]}…' / '{End}' region.");
    begin += Begin.Length;
    return (readme[..begin], readme[begin..end], readme[end..]);
  }

  /// <summary>The generated region, rendered afresh from the descriptors with the hand-written cells of <paramref name="section"/> carried over.</summary>
  public static string Render(string section, IReadOnlyList<IFormatDescriptor> descriptors) {
    ArgumentNullException.ThrowIfNull(section);
    ArgumentNullException.ThrowIfNull(descriptors);
    var (families, rows) = Parse(section);

    var grouped = descriptors
      .GroupBy(d => rows.TryGetValue(d.Id, out var row) ? row.Family : families.LastOrDefault() ?? DefaultFamily)
      .OrderBy(g => families.IndexOf(g.Key) is var i && i >= 0 ? i : int.MaxValue)
      .ThenBy(g => g.Key, StringComparer.Ordinal);

    var page = new StringBuilder();
    page.AppendLine();
    foreach (var family in grouped) {
      page.AppendLine();
      page.Append("### ").AppendLine(family.Key);
      page.AppendLine();
      page.Append("| ").Append(string.Join(" | ", Columns)).AppendLine(" |");
      page.AppendLine(Alignment);
      foreach (var descriptor in family.OrderBy(d => d.DisplayName, StringComparer.OrdinalIgnoreCase).ThenBy(d => d.Id, StringComparer.Ordinal)) {
        rows.TryGetValue(descriptor.Id, out var row);
        page.AppendLine(RenderRow(descriptor, row));
      }
    }
    page.AppendLine();
    return page.ToString().ReplaceLineEndings("\n");
  }

  private static string RenderRow(IFormatDescriptor descriptor, Row? row) {
    var ops = FormatRegistry.GetArchiveOps(descriptor.Id);
    var name = Flatten(descriptor.DisplayName);
    var format = row?.Link is { Length: > 0 } link ? $"[{name}]({link})" : name;
    var cells = new[] {
      format,
      "`" + descriptor.Id + "`",
      State(descriptor),
      Defrag(descriptor, ops),
      Mark(ops is IWipeEmpty),
      Mark(ops is IArchiveShrinkable),
      Mark(ops is ILayoutOptimizable),
      Cell(row?.Proof),
      Cell(row?.Notes),
      Cell(row?.Reference),
    };
    return "| " + string.Join(" | ", cells) + " |";
  }

  /// <summary>The repository's write scale: R/W over WORM over R, read off <see cref="FormatCapabilities"/>.</summary>
  public static string State(IFormatDescriptor descriptor)
    => descriptor.Capabilities.HasFlag(FormatCapabilities.CanModify) ? "R/W"
     : descriptor.Capabilities.HasFlag(FormatCapabilities.CanCreate) ? "WORM"
     : "R";

  /// <summary>
  /// How a format defragments: by moving runs through a block mover of its own,
  /// by writing the volume out again, or not at all.
  /// </summary>
  private static string Defrag(IFormatDescriptor descriptor, IArchiveFormatOperations? ops) {
    if (ops is not IArchiveDefragmentable) return "—";
    if (ops is IFilesystemBlockMover) return "✅ moving";
    var family = descriptor.GetType().Name;
    foreach (var tail in new[] { "FormatDescriptor", "Descriptor" })
      if (family.EndsWith(tail, StringComparison.Ordinal)) { family = family[..^tail.Length]; break; }
    var mover = descriptor.GetType().Assembly.GetTypes()
      .Any(t => t.IsClass && !t.IsAbstract && typeof(IFilesystemBlockMover).IsAssignableFrom(t)
             && t.Name.Equals(family + "BlockMover", StringComparison.Ordinal));
    return mover ? "✅ moving" : "✅ rebuild";
  }

  private static string Mark(bool offered) => offered ? "✅" : "—";
  private static string Cell(string? text) => string.IsNullOrWhiteSpace(text) ? "—" : text.Trim();

  /// <summary>The headings in order, and each row's hand-written cells by id.</summary>
  private static (List<string> Families, Dictionary<string, Row> Rows) Parse(string section) {
    var families = new List<string>();
    var rows = new Dictionary<string, Row>(StringComparer.Ordinal);
    var family = DefaultFamily;
    foreach (var raw in section.ReplaceLineEndings("\n").Split('\n')) {
      var line = raw.Trim();
      if (line.StartsWith("### ", StringComparison.Ordinal)) {
        family = line[4..].Trim();
        if (!families.Contains(family)) families.Add(family);
        continue;
      }
      if (!line.StartsWith('|')) continue;
      var cells = SplitRow(line);
      if (cells.Count != Columns.Length) continue;
      var id = cells[1].Trim('`').Trim();
      if (id.Length == 0 || id == Columns[1] || id.All(c => c == '-' || c == ':')) continue;
      var link = LinkOf(cells[0]);
      rows[id] = new Row(family, link, Blank(cells[7]), Blank(cells[8]), Blank(cells[9]));
    }
    return (families, rows);
  }

  /// <summary>
  /// The address behind a linked name. A Wikipedia address may itself end in a
  /// parenthesis, so the link runs to the cell's last closing one rather than
  /// its first.
  /// </summary>
  private static string? LinkOf(string cell) {
    var open = cell.IndexOf("](", StringComparison.Ordinal);
    var close = cell.LastIndexOf(')');
    return open >= 0 && close > open + 2 ? cell[(open + 2)..close].Trim() : null;
  }

  /// <summary>An empty marker reads back as no text, so a cell nobody filled stays a cell nobody filled.</summary>
  private static string Blank(string cell) => cell.Trim() == "—" ? "" : cell.Trim();

  /// <summary>The cells of a table row; a <c>\|</c> inside a cell is text, not a border.</summary>
  private static List<string> SplitRow(string line) {
    var cells = new List<string>();
    var cell = new StringBuilder();
    var body = line.Trim();
    if (body.StartsWith('|')) body = body[1..];
    if (body.EndsWith('|') && !body.EndsWith("\\|", StringComparison.Ordinal)) body = body[..^1];
    for (var i = 0; i < body.Length; ++i) {
      if (body[i] == '\\' && i + 1 < body.Length && body[i + 1] == '|') { cell.Append("\\|"); ++i; continue; }
      if (body[i] == '|') { cells.Add(cell.ToString().Trim()); cell.Clear(); continue; }
      cell.Append(body[i]);
    }
    cells.Add(cell.ToString().Trim());
    return cells;
  }

  internal static string Flatten(string text)
    => string.Join(" ", text.Split('\n', '\r').Select(l => l.Trim()).Where(l => l.Length > 0))
             .Replace("|", "\\|", StringComparison.Ordinal);
}
