<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FileFormat.Cb7</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FileFormat.SevenZip\FileFormat.SevenZip.csproj" />
    <ProjectReference Include="..\..\Compression.Registry\Compression.Registry.csproj" />
  </ItemGroup>
</Project>
