#pragma warning disable CS1591
using System.Globalization;
using System.Text;

namespace Compression.Tests.Support;

/// <summary>
/// Generates a DOSBox-X <c>dosbox.conf</c> file targeting the validation
/// scenarios in <see cref="DosboxRunner"/>. The conf is intentionally minimal
/// — only the sections we need to drive an MS-DOS 6.22 boot image and run
/// <c>DBLSPACE /CHKDSK</c> against a CVF mounted as a guest drive.
/// <para>
/// Every flag emitted is documented in
/// <a href="https://dosbox-x.com/wiki/Guide%3ADOSBox-X-configuration-file">
/// the DOSBox-X configuration guide</a>. We do NOT reach for undocumented
/// extensions because the user explicitly forbade that.
/// </para>
/// </summary>
public sealed class DosboxConfBuilder {
  private string? _bootImage;
  private string? _hddImage;
  private string? _hddDriveLetter;
  private long _hddSizeBytes;
  private readonly List<string> _autoexecLines = [];
  private string _machine = "svga_s3";
  private string _cycles = "max";

  /// <summary>
  /// Sets the MS-DOS 6.22 boot image (hard-disk image). The DOSBox-X
  /// <c>[autoexec]</c> section will then <c>imgmount c</c> it as <c>C:</c>
  /// using <c>imgmount c &lt;path&gt; -t hdd -fs fat -size 512,63,16,520</c>
  /// (the standard CHS for a ~256 MB FAT16 image; smaller images still mount
  /// fine because DOSBox-X derives the actual geometry from the file size when
  /// it finds an MBR). Caller is responsible for ensuring the image actually
  /// contains <c>DBLSPACE.BIN</c> on its boot partition.
  /// </summary>
  public DosboxConfBuilder MountBootImageAsC(string hostPath) {
    if (string.IsNullOrWhiteSpace(hostPath))
      throw new ArgumentException("Boot image path must be non-empty.", nameof(hostPath));
    this._bootImage = hostPath;
    return this;
  }

  /// <summary>
  /// Mounts a flat hard-disk image (typically our CVF or a wrapper image
  /// containing the CVF as a normal file) as the given drive letter. Uses the
  /// documented <c>imgmount &lt;letter&gt; &lt;path&gt; -t hdd -fs none</c>
  /// form; <c>fs=none</c> is required when the contents are not a recognized
  /// MS-DOS filesystem (which is the case for a raw CVF — it is a sector-level
  /// container, not a FAT filesystem).
  /// </summary>
  public DosboxConfBuilder MountHdd(string hostPath, string driveLetter, long sizeBytes = 0) {
    if (string.IsNullOrWhiteSpace(hostPath))
      throw new ArgumentException("HDD image path must be non-empty.", nameof(hostPath));
    if (string.IsNullOrWhiteSpace(driveLetter) || driveLetter.Length is 0 or > 2)
      throw new ArgumentException("Drive letter must be 1 or 2 characters (e.g. \"D\" or \"D:\").", nameof(driveLetter));
    this._hddImage = hostPath;
    this._hddDriveLetter = driveLetter.TrimEnd(':');
    this._hddSizeBytes = sizeBytes;
    return this;
  }

  /// <summary>
  /// Appends raw DOS commands to the <c>[autoexec]</c> section. Order is
  /// preserved. End the script with <c>EXIT</c> so DOSBox-X with
  /// <c>-exit</c> terminates cleanly.
  /// </summary>
  public DosboxConfBuilder Autoexec(params string[] lines) {
    foreach (var l in lines) {
      if (l is null) continue;
      this._autoexecLines.Add(l);
    }
    return this;
  }

  /// <summary>
  /// Overrides the default machine type. DOSBox-X documents <c>svga_s3</c> as
  /// the default; for some MS-DOS install images <c>vgaonly</c> avoids
  /// chipset-detection delays.
  /// </summary>
  public DosboxConfBuilder Machine(string machineType) {
    if (!string.IsNullOrWhiteSpace(machineType)) this._machine = machineType;
    return this;
  }

  /// <summary>
  /// Sets the cycles strategy. <c>max</c> is fastest but can be unstable for
  /// timing-sensitive code; <c>auto</c> or a fixed value (e.g. <c>50000</c>)
  /// can be specified for repeatability.
  /// </summary>
  public DosboxConfBuilder Cycles(string cyclesValue) {
    if (!string.IsNullOrWhiteSpace(cyclesValue)) this._cycles = cyclesValue;
    return this;
  }

  /// <summary>
  /// Renders the config file to a string. The result is suitable for piping
  /// to <see cref="File.WriteAllText(string, string)"/> and passing to
  /// <c>dosbox-x -conf</c>.
  /// </summary>
  public string Build() {
    var sb = new StringBuilder();

    sb.AppendLine("# Auto-generated by Compression.Tests.Support.DosboxConfBuilder.");
    sb.AppendLine("# Hand-edits will be overwritten on the next test run.");
    sb.AppendLine();

    sb.AppendLine("[sdl]");
    // Documented flags — DOSBox-X 0.83+ honours all four.
    sb.AppendLine("output=surface");
    sb.AppendLine("autolock=false");
    sb.AppendLine("waitonerror=false");
    sb.AppendLine("windowposition=0,0");
    sb.AppendLine();

    sb.AppendLine("[dosbox]");
    sb.AppendLine($"machine={this._machine}");
    sb.AppendLine("memsize=16");
    sb.AppendLine("title=cwb-dblspace-harness");
    sb.AppendLine();

    sb.AppendLine("[cpu]");
    sb.AppendLine("core=auto");
    sb.AppendLine($"cycles={this._cycles}");
    sb.AppendLine();

    sb.AppendLine("[mixer]");
    // Silence audio so headless CI doesn't fail when there is no sound device.
    sb.AppendLine("nosound=true");
    sb.AppendLine();

    sb.AppendLine("[autoexec]");
    sb.AppendLine("@echo off");
    if (!string.IsNullOrEmpty(this._bootImage))
      sb.AppendLine($"imgmount c \"{this._bootImage}\" -t hdd -fs fat");
    if (!string.IsNullOrEmpty(this._hddImage)) {
      var sizeArg = this._hddSizeBytes > 0
        ? $" -size {this._hddSizeBytes.ToString(CultureInfo.InvariantCulture)}"
        : string.Empty;
      sb.AppendLine($"imgmount {this._hddDriveLetter} \"{this._hddImage}\" -t hdd -fs none{sizeArg}");
    }
    foreach (var line in this._autoexecLines)
      sb.AppendLine(line);
    // Belt-and-braces: even if the script forgot, EXIT terminates the session
    // cleanly when DOSBox-X is invoked with -exit.
    if (!this._autoexecLines.Any(l => l.Trim().Equals("EXIT", StringComparison.OrdinalIgnoreCase)))
      sb.AppendLine("EXIT");

    return sb.ToString();
  }
}
