using Compression.Core.DiskImage;
using Compression.Lib.FsConversion;
using Compression.Registry;

namespace Compression.Lib;

/// <summary>
/// Registers all format descriptors with the central registry.
/// The generated partial methods discover descriptors, building blocks and
/// filesystem-driver sidecars across referenced assemblies without reflection.
/// </summary>
public static partial class FormatRegistration {
  private static int _initStarted;
  private static readonly ManualResetEventSlim _initDone = new(initialState: false);

  /// <summary>True iff the registry is fully populated and safe to enumerate.</summary>
  public static bool IsReady => _initDone.IsSet;

  public static System.Threading.Tasks.Task EnsureInitializedAsync() {
    if (_initDone.IsSet) return System.Threading.Tasks.Task.CompletedTask;
    return System.Threading.Tasks.Task.Run(EnsureInitialized);
  }

  public static void EnsureInitialized() {
    if (Interlocked.CompareExchange(ref _initStarted, 1, 0) != 0) {
      _initDone.Wait();
      return;
    }

    try {
      RegisterFormats();
      RegisterCompoundTar();
      RegisterBuildingBlocks();
      RegisterFilesystemDrivers();
      FormatRegistry.Initialize();

      PartitionEditor.InPlaceFilesystemConverter = (stream, srcId, dstId)
        => InPlaceConverter.TryConvert(stream, srcId, dstId)
           is InPlaceConversionResult.Succeeded or InPlaceConversionResult.NoOp;

      PartitionEditor.InPlaceFilesystemResizer = (stream, fsId, newSize, isShrink) => {
        if (!FilesystemResizer.IsSupported(fsId)) return false;
        if (isShrink) FilesystemResizer.Shrink(stream, fsId, newSize);
        else FilesystemResizer.Grow(stream, fsId, newSize);
        return true;
      };
    } finally {
      _initDone.Set();
    }
  }

  /// <summary>Generated by Compression.Registry.Generator.</summary>
  static partial void RegisterFormats();

  /// <summary>Generated by Compression.Registry.Generator.</summary>
  static partial void RegisterBuildingBlocks();

  /// <summary>
  /// Generated by Compression.Registry.Generator. Registers public parameterless
  /// <see cref="IFilesystemDriverAdapter"/> implementations after their format
  /// descriptors and before the registry is finalized.
  /// </summary>
  static partial void RegisterFilesystemDrivers();

  private static void RegisterCompoundTar() {
    FormatRegistry.Register(new CompoundTarDescriptor("TarGz", "tar.gz", "Gzip", ".tar.gz", [".tar.gz", ".tgz"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarBz2", "tar.bz2", "Bzip2", ".tar.bz2", [".tar.bz2", ".tbz2"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarXz", "tar.xz", "Xz", ".tar.xz", [".tar.xz", ".txz"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarZst", "tar.zst", "Zstd", ".tar.zst", [".tar.zst"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarLz4", "tar.lz4", "Lz4", ".tar.lz4", [".tar.lz4"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarLzip", "tar.lz", "Lzip", ".tar.lz", [".tar.lz", ".tlz"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarBr", "tar.br", "Brotli", ".tar.br", [".tar.br", ".tbr"]));
  }
}
