using Compression.Core.DiskImage;
using Compression.Lib.FsConversion;
using Compression.Registry;

namespace Compression.Lib;

/// <summary>
/// Registers all format descriptors with the central registry.
/// The <c>RegisterFormats()</c> partial method is generated at compile time by
/// <c>Compression.Registry.Generator</c>, which discovers all public classes implementing
/// <c>IFormatDescriptor</c> with a parameterless constructor across referenced assemblies.
/// Compound tar descriptors are registered manually since they are composites, not standalone formats.
/// </summary>
public static partial class FormatRegistration {
  private static int _initStarted;
  private static readonly ManualResetEventSlim _initDone = new(initialState: false);

  /// <summary>
  /// Ensures all format descriptors and building blocks are registered exactly once.
  /// Thread-safe: the first caller runs the registration; concurrent callers
  /// WAIT for it to finish (rather than seeing a half-populated
  /// <see cref="FormatRegistry"/>). The earlier "flip flag and return" pattern
  /// caused a race: a background warm-up Task that had set the flag but not
  /// yet finished registering would let a synchronous caller through with an
  /// empty registry, producing "No creatable formats are registered." popups.
  /// </summary>
  public static void EnsureInitialized() {
    if (Interlocked.CompareExchange(ref _initStarted, 1, 0) != 0) {
      // Another thread is already registering — wait for it to finish so the
      // registry is fully populated before we return.
      _initDone.Wait();
      return;
    }

    try {
      RegisterFormats();
      RegisterCompoundTar();
      RegisterBuildingBlocks();
      FormatRegistry.Initialize();

      // Wire the in-place FS-variant converter delegate so PartitionEditor.
      // ConvertFilesystem can dispatch FAT12↔16↔32 and ext2→3→4 conversions
      // without taking a hard dependency on Compression.Lib from Compression.Core.
      PartitionEditor.InPlaceFilesystemConverter = (stream, srcId, dstId)
        => InPlaceConverter.TryConvert(stream, srcId, dstId)
           is InPlaceConversionResult.Succeeded or InPlaceConversionResult.NoOp;

      // Wire the in-place FS-resizer delegate so PartitionEditor.ResizePartition
      // can dispatch FAT shrink/grow and ext shrink/grow without a Core →
      // FileSystem.* dependency.
      PartitionEditor.InPlaceFilesystemResizer = (stream, fsId, newSize, isShrink) => {
        if (!FilesystemResizer.IsSupported(fsId)) return false;
        if (isShrink) FilesystemResizer.Shrink(stream, fsId, newSize);
        else FilesystemResizer.Grow(stream, fsId, newSize);
        return true;
      };
    } finally {
      _initDone.Set();
    }
  }

  /// <summary>
  /// Generated by Compression.Registry.Generator — calls FormatRegistry.Register()
  /// for every discovered format descriptor. Falls back to no-op if generator is not wired up.
  /// </summary>
  static partial void RegisterFormats();

  /// <summary>
  /// Generated by Compression.Registry.Generator — calls BuildingBlockRegistry.Register()
  /// for every discovered building block. Falls back to no-op if generator is not wired up.
  /// </summary>
  static partial void RegisterBuildingBlocks();

  private static void RegisterCompoundTar() {
    FormatRegistry.Register(new CompoundTarDescriptor("TarGz", "tar.gz", "Gzip", ".tar.gz", [".tar.gz", ".tgz"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarBz2", "tar.bz2", "Bzip2", ".tar.bz2", [".tar.bz2", ".tbz2"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarXz", "tar.xz", "Xz", ".tar.xz", [".tar.xz", ".txz"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarZst", "tar.zst", "Zstd", ".tar.zst", [".tar.zst"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarLz4", "tar.lz4", "Lz4", ".tar.lz4", [".tar.lz4"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarLzip", "tar.lz", "Lzip", ".tar.lz", [".tar.lz", ".tlz"]));
    FormatRegistry.Register(new CompoundTarDescriptor("TarBr", "tar.br", "Brotli", ".tar.br", [".tar.br", ".tbr"]));
  }
}
